// This file is auto-generated by scripts/generate_data.js. Do not edit manually.
export const SUBJECTS_DATA = {
  "math1": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  },
  "math2": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  },
  "math3": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  },
  "science_math": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  }
};
