// This file is auto-generated by scripts/generate_data.js. Do not edit manually.
export const SUBJECTS_DATA = {
  "math1": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 1・1\r\n\r\n$a$ は実数の定数とする．方程式\r\n$$\r\n3(a-1)x^2+6x-a-2=0\r\n$$\r\nは $0$ と $1$ の間に少なくとも $1$ つの解をもつことを示せ．\r\n\r\n## 1・2\r\n\r\n$a,\\ b$ は実数とする．2次方程式 $x^2+ax+b=0$ が $0<x<1,\\ 1<x<2$ の範囲に $1$ つずつ解をもつ．このとき，2次方程式 $x^2+bx+a=0$ は異なる $2$ つの実数解をもつことを示し，そのうち大きい方の解のとり得る値の範囲を求めよ．\r\n\r\n## 1・3\r\n\r\n次の連立方程式 $(*)$ を考える．\r\n$$\r\n(*) \\quad \\begin{cases}\r\ny=2x^2-1, \\\\\r\nz=2y^2-1, \\\\\r\nx=2z^2-1\r\n\\end{cases}\r\n$$\r\n(1) $(x,\\ y,\\ z)=(a,\\ b,\\ c)$ が $(*)$ の実数解であるとき，$|a| \\leqq 1,\\ |b| \\leqq 1,\\ |c| \\leqq 1$ であることを示せ．  \r\n(2) $(*)$ は全部で $8$ 組の相異なる実数解 $(x,\\ y,\\ z)$ をもつことを示せ．"
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 2・1\r\n\r\n$k$ を実数とする．3次式 $f(x)=x^3-kx^2-1$ に対し，方程式 $f(x)=0$ の $3$ つの解を $\\alpha,\\ \\beta,\\ \\gamma$ とする．$g(x)$ は $x^3$ の係数が $1$ である $3$ 次式で，方程式 $g(x)=0$ の $3$ つの解が $\\alpha\\beta,\\ \\beta\\gamma,\\ \\gamma\\alpha$ であるものとする．  \r\n(1) $g(x)$ を $k$ を用いて表せ．  \r\n(2) $2$ つの方程式 $f(x)=0$ と $g(x)=0$ が共通の解をもつような $k$ の値を求めよ．\r\n\r\n## 2・2\r\n\r\n$a,\\ b$ は定数（ただし，$b \\neq 0$）とする．整式 $f(x)=x^2+ax+b$ について次の問に答えよ．  \r\n(1) $f(x^2)$ が $f(x)$ で割り切れるような $a,\\ b$ の値をすべて求めよ．  \r\n(2) 任意の自然数 $n$ に対して $f(x^n)$ が $f(x)$ で割り切れるような $a,\\ b$ の値をすべて求めよ．\r\n\r\n## 2・3\r\n\r\n$n$ は正の整数，$p$ は $2$ 以上の整数とする．$f(x),\\ g(x)$ は $n$ 次の整式で，ともに $x^n$ の係数は $1$ とする．このとき，$\\{f(x)\\}^p,\\ \\{g(x)\\}^p$ において\r\n$$\r\nx^{np-1},\\ x^{np-2},\\ \\cdots,\\ x^{np-n}\r\n$$\r\nの係数がそれぞれ一致しているならば，$f(x)=g(x)$ であることを示せ．"
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 3・1\r\n\r\n(1) $a_k,\\ b_k$（$k=1,\\ 2,\\ 3,\\ \\cdots,\\ n$）は実数とし，$A=\\sqrt{\\sum\\limits_{k=1}^n {a_k}^2},\\ B=\\sqrt{\\sum\\limits_{k=1}^n {b_k}^2}$ とおく．$A \\neq 0,\\ B \\neq 0$ のとき，$\\left(\\dfrac{a_k}{A}-\\dfrac{b_k}{B}\\right)^2 \\geqq 0$（$k=1,\\ 2,\\ 3,\\ \\cdots,\\ n$）であることを用いて，不等式 $\\sum\\limits_{k=1}^n a_k b_k \\leqq AB$ が成り立つことを示せ．  \r\n(2) 実数 $a_1,\\ a_2,\\ a_3,\\ a_4,\\ a_5$ が\r\n$$\r\n\\begin{aligned}\r\na_1+a_2+a_3+a_4+a_5 &= 10, \\\\\r\n{a_1}^2+{a_2}^2+{a_3}^2+{a_4}^2+{a_5}^2 &= 25\r\n\\end{aligned}\r\n$$\r\nをともに満たすとき，$a_5$ の最大値を求めよ．\r\n\r\n## 3・2\r\n\r\n$2$ 以上の整数 $k$ に対して，$f_k(x)=x^k-kx+k-1$ とおく．  \r\n(1) $f_k(x)$ は $(x-1)^2$ で割り切れることを示せ．  \r\n(2) $n$ は $2$ 以上の整数とする．$n$ 次多項式 $g(x)$ が $(x-1)^2$ で割り切れるためには，$g(x)$ が定数 $a_2,\\ a_3,\\ a_4,\\ \\cdots,\\ a_n$ を用いて\r\n$$\r\ng(x)=\\sum_{k=2}^n a_k f_k(x)\r\n$$\r\nの形に表されることが必要十分であることを示せ．\r\n\r\n## 3・3\r\n\r\n$\\alpha=2\\cos 20^\\circ$ とおくとき，次の問に答えよ．  \r\n(1) $\\alpha$ は $3$ 次方程式 $x^3-3x-1=0$ の解であることを示せ．  \r\n(2) $\\alpha$ は無理数であることを示せ．  \r\n(3) $\\alpha$ を解にもつ $2$ 次方程式 $ax^2+bx+c=0$（$a,\\ b,\\ c$ は有理数）は存在しないことを示せ．"
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 4・1\r\n\r\n$n$ は正の整数とする．正の整数 $k$ に対して $\\left(k+\\dfrac{1}{4}\\right)^2$ に最も近い整数を $a_k$ とするとき，\r\n$$\r\n\\sum_{k=1}^n (a_k-k^2)\r\n$$\r\nを $n$ で表せ．\r\n\r\n## 4・2\r\n\r\n数列 $\\{a_n\\}$ があって $a_1=2,\\ a_2=4$ であり，連続する $3$ 項 $a_n,\\ a_{n+1},\\ a_{n+2}$ は $n$ が奇数のとき等差数列をなし，$n$ が偶数のとき等比数列をなす．  \r\n(1) $m$ を正の整数とする．$a_{2m-1},\\ a_{2m}$ を求めよ．  \r\n(2) $n$ を正の整数として，$a_1$ から $a_{2n}$ までの総和を求めよ．\r\n\r\n## 4・3\r\n\r\n$n$ は $3$ 以上の整数とする．実数 $x_1,\\ x_2,\\ x_3,\\ \\cdots,\\ x_n$ が条件\r\n$$\r\nx_{k-1}-2x_k+x_{k+1}>0 \\quad (2 \\leqq k \\leqq n-1)\r\n$$\r\nを満たすとし，$x_1,\\ x_2,\\ x_3,\\ \\cdots,\\ x_n$ の最小値を $m$ とする．  \r\nこのとき，$x_l=m$ となる整数 $l$（$1 \\leqq l \\leqq n$）の個数は $1$ または $2$ であることを示せ．"
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 5・1\r\n\r\n平面上に互いに外接する半径 $1$ の $2$ つの円 $T$ と $S_1$ がある．$T$ に点 $\\mathrm{P}$ で接し，$S_1$ に点 $\\mathrm{Q}_1$ で接する図のような直線 $l$ を考える．$l,\\ T,\\ S_1$ の $3$ つで囲まれた領域内に中心をもち，$l,\\ T,\\ S_1$ のすべてに接する円を $S_2$ とし，$S_2$ と $l$ との接点を $\\mathrm{Q}_2$ とする．一般に，$n=2,\\ 3,\\ 4,\\ \\cdots$ に対して，$l,\\ T,\\ S_{n-1}$ の $3$ つで囲まれた領域内に中心をもち，$l,\\ T,\\ S_{n-1}$ のすべてに接する円を $S_n$ とし，$S_n$ と $l$ との接点を $\\mathrm{Q}_n$ とする．また，$S_n$ の半径を $r_n$ とし，線分 $\\mathrm{PQ}_n$ の長さを $q_n$ とする．  \r\n(1) $r_n$ を $q_n$ を用いて表せ．  \r\n(2) $q_n,\\ r_n$ をそれぞれ $n$ を用いて表せ．\r\n\r\n## 5・2\r\n\r\n正の整数 $n$ に対して，\r\n$$\r\n(1+\\sqrt{2})^n = x_n+y_n\\sqrt{2}\r\n$$\r\nが成り立つように整数 $x_n,\\ y_n$ を定める．  \r\n(1) $x_{n+1},\\ y_{n+1}$ を $x_n,\\ y_n$ で表せ．  \r\n(2) ${x_n}^2-2{y_n}^2=(-1)^n$ であることを示せ．  \r\n(3) 任意の正の整数 $n$ に対して，$\\dfrac{x_{n+1}}{y_{n+1}}$ は $\\dfrac{x_n}{y_n}$ よりも $\\sqrt{2}$ のよい近似であることを示せ．\r\n\r\n## 5・3\r\n\r\n数列 $\\{x_n\\}$ が次のように定義されている．\r\n$$\r\nx_1=0,\\ k=1,\\ 2,\\ 3,\\ \\cdots \\text{に対して，}\r\n$$\r\n$$\r\nx_n = \\begin{cases}\r\nx_k+1 & (n=2k \\text{ のとき}) \\\\\r\nx_k+2 & (n=2k+1 \\text{ のとき})\r\n\\end{cases}\r\n$$\r\nこのとき，$n=2,\\ 3,\\ 4,\\ \\cdots$ に対して，$x_n \\leqq 2\\log_2 n - 1$ が成り立つことを示せ．"
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 6・1\r\n\r\n$f(x)=x^3-3x^2+2x$ とおく．曲線 $y=f(x)$ 上の点 $\\mathrm{P}_n(x_n,\\ f(x_n))$（$n$ は自然数）を次の条件 (a), (b) で定める．  \r\n(a) $\\mathrm{P}_1$ を $(0,\\ 0)$ とする．  \r\n(b) $n \\geqq 1$ について，$\\mathrm{P}_n$ における曲線 $y=f(x)$ の接線は，$\\mathrm{P}_n$ 以外の $1$ 点でこの曲線と交わる．この交点を $\\mathrm{P}_{n+1}$ とおく．  \r\n(1) $x_n$ と $x_{n+1}$ の関係式を求めよ．  \r\n(2) $\\lim\\limits_{n \\to \\infty}\\dfrac{x_{n+1}}{x_n}$ を求めよ．\r\n\r\n## 6・2\r\n\r\n数列 $\\dfrac{1}{1},\\ \\dfrac{1}{2},\\ \\dfrac{2}{2},\\ \\dfrac{1}{3},\\ \\dfrac{2}{3},\\ \\dfrac{3}{3},\\ \\dfrac{1}{4},\\ \\dfrac{2}{4},\\ \\dfrac{3}{4},\\ \\dfrac{4}{4},\\ \\dfrac{1}{5},\\ \\cdots$ の初項から第 $n$ 項までのうちで値が $\\dfrac{1}{4}$ に等しい項の個数を $a_n$ とするとき，$\\lim\\limits_{n \\to \\infty}\\dfrac{a_n}{\\sqrt{n}}$ を求めよ．\r\n\r\n## 6・3\r\n\r\n(1) $n$ 桁の自然数のうち，各位の数字がすべて $1$ と異なるものの個数を求めよ．  \r\n(2) 自然数の逆数からなる級数\r\n$$\r\n\\dfrac{1}{1}+\\dfrac{1}{2}+\\dfrac{1}{3}+\\cdots+\\dfrac{1}{m}+\\cdots\r\n$$\r\nから，分母に数字 $1$ が現れる項をすべて除いて得られる級数\r\n$$\r\n\\dfrac{1}{2}+\\dfrac{1}{3}+\\dfrac{1}{4}+\\dfrac{1}{5}+\\dfrac{1}{6}+\\dfrac{1}{7}+\\dfrac{1}{8}+\\dfrac{1}{9}+\\dfrac{1}{20}+\\dfrac{1}{22}+\\dfrac{1}{23}+\\cdots\r\n$$\r\nについて，その部分和は，$40$ を超えないことを示せ．"
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 7・1\r\n\r\n七角柱の $9$ 個の面に $1$ から $9$ までの番号が書いてあるものとする．この $9$ 個の面に $1$ つずつ，異なる $4$ 色の中から $1$ 色ずつ選んでは塗っていく．このとき，どの辺を共有する $2$ 面の組も同一色では塗られない塗り方の数を求めよ．\r\n\r\n## 7・2\r\n\r\n(1) 正九角形の $3$ つの頂点でできる ${}_9\\mathrm{C}_3$（$=84$）個の三角形のうち，鈍角三角形は全部でいくつあるか．  \r\n(2) $n$ は正の整数とする．正 $2n+1$ 角形の $3$ つの頂点でできる ${}_{2n+1}\\mathrm{C}_3$ 個の三角形のうち，鈍角三角形は全部でいくつあるか．\r\n\r\n## 7・3\r\n\r\n$n$ を正の整数とし，$n$ 個のボールを $3$ つの箱に分けて入れる問題を考える．ただし，$1$ 個のボールも入らない箱があってもよいものとする．  \r\n(1) $1$ から $n$ まで相異なる番号のついた $n$ 個のボールを，区別のつかない $3$ つの箱に入れる場合，その入れ方は全部で何通りあるか．  \r\n(2) $n=6m$（$m$ は正の整数）であるとき，区別のつかない $n$ 個のボールを，区別のつかない $3$ つの箱に入れる場合，その入れ方は全部で何通りあるか．$m$ で表せ．"
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 8・1\r\n\r\n$n$ を $3$ 以上の奇数とする．袋の中に番号 $0,\\ 1,\\ 2,\\ \\cdots,\\ n$ のついた札がそれぞれ $1$ 枚ずつ入っている．この袋から $2$ 枚の札を取り出したとき，それらの札の番号の和を $n$ で割った余りが $k$ である確率を求めよ．ただし，$k$ は $0 \\leqq k \\leqq n-1$ を満たす整数とする．\r\n\r\n## 8・2\r\n\r\n数直線上を動く点があり，はじめは原点 $\\mathrm{O}$ にある．サイコロを振り，$1$ または $2$ の目が出たら $+1$ だけ移動させ，$3$ または $4$ の目が出たら動かさず，$5$ または $6$ の目が出たら $-1$ だけ移動させる．サイコロを $6$ 回振るとき，点が $6$ 回目にはじめて座標 $2$ の点に移動する確率を求めよ．\r\n\r\n## 8・3\r\n\r\n数 $1,\\ 2,\\ 3,\\ \\cdots,\\ 2a$（$a$ は正の整数）のいずれについても，それが記入されたカードが $1$ 枚ずつ，計 $2a$ 枚のカードが箱に入っている．ここから無作為にカードを $1$ 枚取り出して記入された数を記録してもとに戻す操作を $b$ 回（$b$ は $2$ 以上の整数）行う．  \r\n記録された $b$ 個の数の最大値 $M$ と最小値 $m$ について，$M \\leqq 2m$ となる確率を $a,\\ b$ で表せ．"
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 9・1\r\n\r\n$\\boxed{1},\\ \\boxed{2},\\ \\boxed{3}$ という $3$ 枚のカードがこの順に横一列に並んでいる．サイコロを振って，$3$ の倍数の目が出たら左端のカードと中央のカードを入れ換え，その他の目が出たら右端のカードと中央のカードを入れ換える．  \r\nこの試行を $n$ 回（$n$ は正の整数）繰り返したのち，$\\boxed{2}$ が中央にある確率 $a_n$ を $n$ で表せ．\r\n\r\n## 9・2\r\n\r\n$n$ は $3$ 以上の整数とする．箱の中に $n$ 個の球があり，連続した整数 $a,\\ a+1,\\ a+2,\\ \\cdots,\\ a+n-1$ がそれぞれの球に $1$ つずつ記されている．以下では，$n$ の値は知られているが，$a$ の値は知られていないものとする．  \r\n(1) この箱から無作為に $1$ 個の球を取り出し，記されている整数を調べる．ただし，取り出された球は箱に戻さない．これを繰り返して $X$ 回目（$X$ は正の整数）に初めて $a$ の値がわかるものとする．  \r\nこのとき，$X$ の期待値を求めよ．  \r\n(2) この箱から無作為に $1$ 個の球を取り出し，記されている整数を調べて箱に戻すことを $k$ 回（$k$ は正の整数）繰り返す．この操作により $a$ の値がわかる確率を求めよ．\r\n\r\n## 9・3\r\n\r\n$N$ を正の整数とする．袋の中に赤玉 $1$ 個と白玉 $2$ 個が入っている．「この袋から玉を $1$ 個取り出して戻し，出た玉と同じ色の玉を袋の中に $1$ 個追加する」という操作を $N$ 回繰り返した後，赤玉が袋の中にちょうど $m$ 個（$1 \\leqq m \\leqq N+1$）ある確率を $N,\\ m$ を用いて表せ．"
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 10・1\r\n\r\n正の数 $s,\\ t$ に対して，$x$ の $4$ 次方程式\r\n$$\r\n\\text{(A)} \\quad x^4-2(s+t-1)x^2+2st+1=0\r\n$$\r\nを考える．  \r\n(1) 方程式 (A) が異なる $4$ つの実数解をもつような $(s,\\ t)$ の存在する範囲を，$st$ 平面上に図示せよ．  \r\n(2) $\\dfrac{1}{2} \\leqq t \\leqq 2$ であるすべての $t$ に対して，方程式 (A) が異なる $4$ つの実数解をもつとき，$s$ の値の範囲を求めよ．  \r\n(3) $\\dfrac{1}{2} \\leqq t \\leqq 2$ である少なくとも $1$ つの $t$ に対して，方程式 (A) が異なる $4$ つの実数解をもつとき，$s$ の値の範囲を求めよ．\r\n\r\n## 10・2\r\n\r\n正方形のタイル $n$ 枚（$n \\geqq 2$）が $1$ 列に並べてある．$6$ 色の塗料の全て，またはこのうちの何色かを用いてこの $n$ 枚のタイルを塗る．  \r\n(1) 隣り合う $2$ 枚のタイルの色がすべて異なるような塗り方の数 $a_n$ を求めよ．  \r\n(2) 隣り合う $2$ 枚のタイルの色がすべて異なり，かつ両端のタイルの色が異なるような塗り方の数を $b_n$ とする．$b_n$ を求めよ．\r\n\r\n## 10・3\r\n\r\n袋の中に，青色のカードが $4$ 枚，黄色のカードが $3$ 枚，赤色のカードが $1$ 枚の計 $8$ 枚のカードが入っている．この袋から無作為にカードを $1$ 枚取り出して，その色を記録し袋に戻す試行を繰り返し行う．ただし，赤色のカードが取り出された場合はその回で試行を終了する．また，黄色のカードが $2$ 回連続して取り出された場合もその回で試行を終了する．このとき，ちょうど $n$ 回目（$n \\geqq 1$）に試行を終了する確率を求めよ．"
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 11・1\r\n\r\n$n$ 次の整式 $f(x)=a_0+a_1 x+a_2 x^2+\\cdots+a_n x^n$（$a_0,\\ a_1,\\ a_2,\\ \\cdots,\\ a_n$ は定数，$a_n \\neq 0$）が次の条件を満たしている．\r\n$$\r\n\\begin{array}{cl}\r\n\\text{(i)} & f(1)=1 \\\\\r\n\\text{(ii)} & f(1-x)=f(x) \\\\\r\n\\text{(iii)} & x^n f\\left(\\dfrac{1}{x}\\right)=f(x)\r\n\\end{array}\r\n$$\r\n(1) $a_0$ の値を求めよ．  \r\n(2) $f(x)$ を求めよ．\r\n\r\n## 11・2\r\n\r\n$1$ つのサイコロを繰り返し $6$ 回投げ，出た目を順に $a,\\ b,\\ c,\\ d,\\ e,\\ f$ とする．  \r\n(1) $a,\\ b$ をこの順に並べて十進法で表された $2$ 桁の整数\r\n$$\r\nN_2=ab \\ (=10a+b)\r\n$$\r\nを作る．$N_2$ が $7$ の倍数となる確率を求めよ．  \r\n(2) $a,\\ b,\\ c$ をこの順に並べて十進法で表された $3$ 桁の整数\r\n$$\r\nN_3=abc \\ (=100a+10b+c)\r\n$$\r\nを作る．$N_3$ が $7$ の倍数となる確率を求めよ．  \r\n(3) $a,\\ b,\\ c,\\ d,\\ e,\\ f$ をこの順に並べて十進法で表された $6$ 桁の整数 $N_6=abcdef$ を作る．$N_6$ が $7$ の倍数となる確率を求めよ．\r\n\r\n## 11・3\r\n\r\n$\\mathrm{A},\\ \\mathrm{B},\\ \\mathrm{C}$ の $3$ つのチームが参加する野球の大会を開催する．以下の方式で試合を行い，$2$ 連勝したチームが出た時点で，そのチームを優勝チームとして大会は終了する．  \r\n(a) $1$ 試合目で $\\mathrm{A}$ と $\\mathrm{B}$ が対戦する．  \r\n(b) $2$ 試合目で，$1$ 試合目の勝者と，$1$ 試合目で待機していた $\\mathrm{C}$ が対戦する．  \r\n(c) $k$ 試合目で優勝チームが決まらない場合は，$k$ 試合目の勝者と，$k$ 試合目で待機していたチームが $k+1$ 試合目で対戦する．ここで $k$ は $2$ 以上の整数とする．  \r\nなお，すべての対戦において，それぞれのチームが勝つ確率は $\\dfrac{1}{2}$ で，引き分けはないものとする．  \r\n(1) $n$ を $2$ 以上の整数とする．ちょうど $n$ 試合目で $\\mathrm{A}$ が優勝する確率を求めよ．  \r\n(2) $m$ を正の整数とする．総試合数が $3m$ 以下で $\\mathrm{A}$ が優勝したとき，$\\mathrm{A}$ の最後の対戦相手が $\\mathrm{B}$ である条件付き確率を求めよ．"
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 12・1\r\n\r\n正の実数 $x,\\ y$ が $\\dfrac{x^2+xy+2y^2}{x^2-xy+2y^2} \\geqq 2$ を満たしながら変化するとき，次の問に答えよ．  \r\n(1) $t=\\dfrac{x}{y}$ のとり得る値の範囲を求めよ．  \r\n(2) 不等式 $x^3-3axy^2+a^2 y^3 \\geqq 0$ がつねに成り立つための正の実数 $a$ に関する条件を求めよ．\r\n\r\n## 12・2\r\n\r\n正の整数 $a$ と $b$ は互いに素であるとし，正の整数からなる数列 $\\{x_n\\}$ を\r\n$$\r\nx_1=x_2=1, \\quad x_{n+2}=ax_{n+1}+bx_n \\quad (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nで定める．このときすべての正の整数 $n$ に対して $x_{n+1}$ と $x_n$ が互いに素であることを示せ．\r\n\r\n## 12・3\r\n\r\n$1$ から $n$ までの番号がついている $n$ 個の箱と，$1$ から $n$ までの番号がついている $n$ 個の球があり，それぞれの箱に球を $1$ 個ずつ無作為に入れるものとする．箱の番号と球の番号がすべて異なる入れ方の総数を $D_n$ とするとき，次の問に答えよ．  \r\n(1) $D_4$ を求めよ．  \r\n(2) $D_n,\\ D_{n-1},\\ D_{n-2}$（$n \\geqq 3$）の間に成り立つ関係式を求めよ．  \r\n(3) 箱の番号と球の番号がすべて異なる確率を $P_n$ とするとき，\r\n$$\r\nP_n=\\dfrac{1}{2!}-\\dfrac{1}{3!}+\\dfrac{1}{4!}-\\dfrac{1}{5!}+\\cdots+\\dfrac{(-1)^n}{n!} \\quad (n \\geqq 2)\r\n$$\r\nが成り立つことを示せ．"
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 13・1\r\n\r\n$4$ 枚のカードがあって，$1$ から $4$ までの整数が $1$ つずつ書かれている．このカードから $1$ 枚引いて，カードに書かれた整数を記録し，カードをもとに戻す．この試行を $n$ 回繰り返し，記録した順に整数を並べて得られる数列を，$a_1,\\ a_2,\\ \\cdots,\\ a_n$ とする．  \r\n(1) $n$ は $2$ 以上の整数とする．\r\n$$\r\na_1 \\leqq a_2 \\leqq \\cdots \\leqq a_n\r\n$$\r\nとなる確率を求めよ．  \r\n(2) $n$ は $3$ 以上の整数とする．\r\n$$\r\na_1 \\leqq a_2 \\leqq \\cdots \\leqq a_{n-1} \\quad \\text{かつ} \\quad a_{n-1} > a_n\r\n$$\r\nとなる確率を求めよ．\r\n\r\n## 13・2\r\n\r\n(1) $a<b,\\ c<d$ に対して，$ad+bc<ac+bd$ が成り立つことを示せ．  \r\n(2) $n$ は正の整数とする．  \r\n正の整数 $1,\\ 2,\\ 3,\\ \\cdots,\\ n$ について，その順列を考え，並んだ正の整数を先頭から順に $a_1,\\ a_2,\\ a_3,\\ \\cdots,\\ a_n$ とし，\r\n$$\r\nS_n = \\sum_{k=1}^n k a_k\r\n$$\r\nとする．  \r\n$S_n$ を最大にする $a_1,\\ a_2,\\ a_3,\\ \\cdots,\\ a_n$ を求めよ．\r\n\r\n## 13・3\r\n\r\n$1$ から $n$（$n \\geqq 3$）までのすべての整数を $1$ つずつ書いた $n$ 枚のカードの中から，同時に $3$ 枚のカードを取り出す．取り出した $3$ 枚のカードに書いてある数をそれぞれの長さとする $3$ つの線分で，三角形を作ることを考える．三角形ができるようなカードの取り出し方の場合の数を $S_n$，三角形ができる確率を $P_n$ とするとき，次の問に答えよ．  \r\n(1) $S_{n+1}-S_n$ を $n$ を用いて表せ．  \r\n(2) $m$ は $2$ 以上の整数とする．$P_{2m}$ および $\\lim\\limits_{m \\to \\infty} P_{2m}$ を求めよ．"
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 14・1\r\n\r\n$n=1,\\ 2,\\ 3,\\ \\cdots$ に対して $x$ の整式 $P_n(x)=x^3-nx^2-(2n+12)x-8$ を考える．  \r\n(1) 3次方程式 $P_n(x)=0$ の正の実数解はただ $1$ つであることを示せ．  \r\n(2) $t$ が $P_n(x)=0$ の解であるとき，$P_n\\left(-\\dfrac{4}{t+2}\\right)$ を求めよ．  \r\n(3) $P_n(x)=0$ の正の実数解を $\\alpha_n$ とするとき，$P_n(x)=0$ の最小の実数解 $\\beta_n$ を $\\alpha_n$ で表せ．さらに，$\\lim\\limits_{n \\to \\infty} \\beta_n$ を求めよ．\r\n\r\n## 14・2\r\n\r\n数列 $\\{a_n\\}$ は，\r\n$$\r\n\\sum_{k=1}^n a_k = \\left(a_n+\\dfrac{1}{4}\\right)^2 \\quad (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nを満たしている．  \r\n(1) $\\{a_n\\}$ の項はすべて正とする．一般項 $a_n$ を求めよ．  \r\n(2) $\\{a_n\\}$ の最初の $100$ 項のうち，$1$ つは負で他はすべて正とする．$a_{100}$ を求めよ．\r\n\r\n## 14・3\r\n\r\n$1$ と $0$ を $5$ 個並べた列 $10110$ をある人が繰り返し書き写すとする．ただし，この列を $S$ で表し，これの第 $1$ 回の写しを $S_1$ で表すとき，第 $2$ 回目に書き写すときは $S_1$ を書き写す．$S_1$ の写しを $S_2$ とするとき，第 $3$ 回目には $S_2$ を書き写す．以下，同様に続ける．  \r\nこの人が $0$ を $1$ に写しまちがえる確率は $p$（$0<p<1$）であり，$1$ を $0$ に写しまちがえる確率は $q$（$0<q<1$）であるが，それ以外の写しまちがいはないものとする．  \r\n第 $n$ 回目の写し $S_n$ が $S$ に一致する確率を $C(n)$ とするとき，極限値 $\\lim\\limits_{n \\to \\infty} C(n)$ を求めよ．"
      }
    }
  },
  "math2": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 1・1\r\n\r\n$xy$ 平面上の点 $(2,\\ t)$ を中心として原点 $\\mathrm{O}(0,\\ 0)$ を通る円を $C_t$ とし，$C_t$ が円 $x^2+y^2=4$ と交わる点を $\\mathrm{P},\\ \\mathrm{Q}$ とする．  \r\n(1) 直線 $\\mathrm{PQ}$ が，$t$ の値にかかわらず通る点の座標を求めよ．  \r\n(2) $t$ が実数全体を動くとき，線分 $\\mathrm{PQ}$ の中点 $\\mathrm{R}$ の軌跡を求め，$xy$ 平面上に図示せよ．\r\n\r\n## 1・2\r\n\r\n実数 $x,\\ y$ は $x \\leqq 1,\\ y \\leqq 1,\\ x^2+y^2 \\leqq 2$ を満たして変化する．  \r\n(1) 点 $(x+y,\\ xy)$ の動く範囲を図示せよ．  \r\n(2) $2xy-x-y$ のとり得る値の範囲を求めよ．\r\n\r\n## 1・3\r\n\r\n$\\mathrm{O}$ を原点とする $xy$ 平面上に，曲線 $C_1\\colon y=x^2$ と，$\\mathrm{O}$ を中心とする半径 $1$ の円 $C_2$ がある．$C_1$ 上の異なる $2$ 点 $\\mathrm{P},\\ \\mathrm{Q}$ が，直線 $\\mathrm{PQ}$ が $C_2$ と接するように動くとき，$\\mathrm{P},\\ \\mathrm{Q}$ における $C_1$ の接線の交点 $\\mathrm{R}$ の軌跡を求め，$xy$ 平面上に図示せよ．"
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 2・1\r\n\r\n頂点が曲線 $C\\colon y=x^2$（$x \\geqq 0$）上にあるように，放物線 $y=-\\dfrac{1}{3}x^2$ を平行移動したものを $P$ とする．$P$ の頂点を $C$ 上で動かすとき，$P$ が通過する領域を求め，図示せよ．\r\n\r\n## 2・2\r\n\r\n放物線 $C_1\\colon y=x^2$ と円 $C_2\\colon x^2+(y-a)^2=\\dfrac{1}{2}a^2+\\dfrac{1}{8}$（$a$ は実数）がある．$C_1,\\ C_2$ の共有点の個数を $N$ として，次の問に答えよ．  \r\n(1) $N=2$ となるような $a$ の値の範囲を求めよ．  \r\n(2) $N=1$ となるような $a$ の値を求めよ．\r\n\r\n## 2・3\r\n\r\n$xy$ 平面上に，楕円 $E\\colon \\dfrac{(x-3)^2}{5^2}+\\dfrac{y^2}{4^2}=1$ とその内部に含まれる円 $C\\colon x^2+y^2=1$ がある．$C$ の外部にある点 $\\mathrm{P}(p,\\ q)$ から $C$ へ引いた $2$ 本の接線の接点を通る直線を $l$ として，次の問に答えよ．  \r\n(1) $l$ の方程式を求めよ．  \r\n(2) $\\mathrm{P}$ が $E$ 上を動くとき，どの $l$ も通らないような点の存在範囲を求め，図示せよ．"
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 3・1\r\n\r\n$a$ は $a \\geqq 0$ を満たす定数とする．原点 $\\mathrm{O}$ を極，$x$ 軸の正の部分を始線とする極座標 $(r,\\ \\theta)$ を定めたとき，極方程式\r\n$$\r\n\\dfrac{1}{r}=2\\cos\\theta+a\r\n$$\r\nで定められる図形を $C_a$ とする．  \r\n(1) $C_0$ は直線となることを示せ．  \r\n(2) $a>0$ とする．$C_a$ 上の点 $\\mathrm{P}$ から $C_0$ に下ろした垂線の足を $\\mathrm{H}$ とする．$\\mathrm{P}$ が $C_a$ 上を動くとき，$\\dfrac{\\mathrm{PH}}{\\mathrm{OP}}$ は一定であることを示せ．  \r\n(3) $C_a$ が $\\mathrm{O}$ を焦点，$C_0$ を準線とする放物線となるように $a$ の値を定めよ．\r\n\r\n## 3・2\r\n\r\n$xy$ 平面上に，$2$ つの双曲線\r\n$$\r\nC_1\\colon x^2-y^2=1,\\quad C_2\\colon x^2-y^2=-1\r\n$$\r\nがある．$C_1$ 上の点 $\\mathrm{P}(p,\\ q)$（$p>0$）に対して，$C_1$ の $\\mathrm{P}$ における接線 $l_1$ と $C_2$ の $2$ つの交点を $\\mathrm{Q},\\ \\mathrm{Q}'$ とし，$C_2$ の $\\mathrm{Q}$ における接線 $l_2$ と $C_2$ の $\\mathrm{Q}'$ における接線 $l_2'$ の交点を $\\mathrm{R}$ とする．  \r\n(1) $\\mathrm{R}$ の座標は，$(-p,\\ -q)$ であることを示せ．  \r\n(2) 三角形 $\\mathrm{QQ}'\\mathrm{R}$ の面積が一定であることを示し，その値を求めよ．\r\n\r\n## 3・3\r\n\r\n円 $x^2+y^2=1$ を $C_0$，楕円 $\\dfrac{x^2}{a^2}+\\dfrac{y^2}{b^2}=1$（$a>0,\\ b>0$）を $C_1$ とする．$C_1$ 上のどのような点 $\\mathrm{P}$ に対しても，$\\mathrm{P}$ を頂点にもち $C_0$ に外接して $C_1$ に内接する平行四辺形が存在するための必要十分条件を，$a,\\ b$ を用いて表せ．"
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 4・1\r\n\r\nベクトル $\\vec{a},\\ \\vec{b}$ が，$|\\vec{a}+2\\vec{b}|=1,\\ |2\\vec{a}+\\vec{b}|=1$ を満たすとき，$|\\vec{a}-3\\vec{b}|$ のとり得る値の範囲を求めよ．\r\n\r\n## 4・2\r\n\r\n$xy$ 平面の原点 $\\mathrm{O}$ を中心とする半径 $1$ の円を $C$ とし，$C$ 上に定点 $\\mathrm{A}$ をとる．  \r\n$C$ 上の点 $\\mathrm{X}$ に対し，\r\n$$\r\n\\vec{\\mathrm{OY}}+(\\vec{\\mathrm{OA}}\\cdot\\vec{\\mathrm{OX}})\\vec{\\mathrm{OX}}=\\vec{0}\r\n$$\r\nを満たす平面上の点 $\\mathrm{Y}$ を考える．ただし，$\\vec{\\mathrm{OA}}\\cdot\\vec{\\mathrm{OX}}$ は $\\vec{\\mathrm{OA}}$ と $\\vec{\\mathrm{OX}}$ の内積である．  \r\n(1) $\\mathrm{X}$ が $C$ 上を動くとき，$\\mathrm{Y}$ はある定円 $C'$ 上を動くことを示せ．  \r\n(2) $\\mathrm{X}$ が $C$ 上を $1$ 周するとき，$\\mathrm{Y}$ は $C'$ 上を $2$ 周することを示せ．\r\n\r\n## 4・3\r\n\r\n(1) 平面上で $\\vec{0}$ でないベクトル $\\vec{a},\\ \\vec{b},\\ \\vec{c}$ が，\r\n$$\r\n\\dfrac{\\vec{a}}{|\\vec{a}|}+\\dfrac{\\vec{b}}{|\\vec{b}|}+\\dfrac{\\vec{c}}{|\\vec{c}|}=\\vec{0}\r\n$$\r\nを満たすとき，$\\vec{a}$ と $\\vec{b}$，$\\vec{b}$ と $\\vec{c}$，$\\vec{c}$ と $\\vec{a}$ のなす角をそれぞれ求めよ．  \r\n(2) $\\vec{a}$（$\\ne \\vec{0}$），$\\vec{x}$ を平面上のベクトルとするとき，\r\n$$\r\n|\\vec{a}-\\vec{x}| \\geqq |\\vec{a}|-\\vec{x}\\cdot\\dfrac{\\vec{a}}{|\\vec{a}|}\r\n$$\r\nであることを示せ．ここで，$\\vec{x}\\cdot\\dfrac{\\vec{a}}{|\\vec{a}|}$ は $\\vec{x}$ と $\\dfrac{\\vec{a}}{|\\vec{a}|}$ の内積を表す．  \r\n(3) すべての内角が $120^\\circ$ 未満の三角形 $\\mathrm{ABC}$ がある．点 $\\mathrm{O}$ は三角形 $\\mathrm{ABC}$ の内部の点で，\r\n$$\r\n\\dfrac{\\vec{\\mathrm{OA}}}{|\\vec{\\mathrm{OA}}|}+\\dfrac{\\vec{\\mathrm{OB}}}{|\\vec{\\mathrm{OB}}|}+\\dfrac{\\vec{\\mathrm{OC}}}{|\\vec{\\mathrm{OC}}|}=\\vec{0}\r\n$$\r\nを満たす点とする．また，三角形 $\\mathrm{ABC}$ の内部を動く点 $\\mathrm{X}$ から各頂点までの距離の和を $L=|\\vec{\\mathrm{XA}}|+|\\vec{\\mathrm{XB}}|+|\\vec{\\mathrm{XC}}|$ とする．このとき，$L$ が最小となるような $\\mathrm{X}$ が存在し，その $\\mathrm{X}$ は $\\mathrm{O}$ と一致することを示せ．"
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 5・1\r\n\r\n一辺の長さが $1$ の正四面体 $\\mathrm{OABC}$ に対して，点 $\\mathrm{P}$ が\r\n$$\r\n2\\vec{\\mathrm{OP}}=3\\vec{\\mathrm{AP}}+\\vec{\\mathrm{BP}}\r\n$$\r\nを満たしている．点 $\\mathrm{P}$ から平面 $\\mathrm{OBC}$ に垂線を下ろし，その垂線と平面 $\\mathrm{OBC}$ の交点を $\\mathrm{Q}$ とする．また，直線 $\\mathrm{PQ}$ と平面 $\\mathrm{ABC}$ の交点を $\\mathrm{R}$ とする．$\\vec{a}=\\vec{\\mathrm{OA}},\\ \\vec{b}=\\vec{\\mathrm{OB}},\\ \\vec{c}=\\vec{\\mathrm{OC}}$ とおくとき，次の問に答えよ．  \r\n(1) $\\vec{\\mathrm{OP}}$ を $\\vec{a},\\ \\vec{b}$ を用いて表せ．  \r\n(2) $\\vec{\\mathrm{PQ}}$ を $\\vec{a},\\ \\vec{b},\\ \\vec{c}$ を用いて表せ．  \r\n(3) $\\mathrm{PQ}\\colon\\mathrm{QR}$ を求めよ．\r\n\r\n## 5・2\r\n\r\n各面がすべて鋭角三角形である四面体 $\\mathrm{ABCD}$ がある．点 $\\mathrm{P}$ が辺 $\\mathrm{AB}$ 上にあり，点 $\\mathrm{Q}$ が三角形 $\\mathrm{ABC}$ の周上にあるとき，\r\n$$\r\n\\vec{\\mathrm{AB}}\\cdot\\vec{\\mathrm{DA}} \\leqq \\vec{\\mathrm{AP}}\\cdot\\vec{\\mathrm{DQ}} \\leqq \\vec{\\mathrm{AB}}\\cdot\\vec{\\mathrm{DB}}\r\n$$\r\nが成り立つことを証明せよ．\r\n\r\n## 5・3\r\n\r\n四面体 $\\mathrm{ABCD}$ があり，辺 $\\mathrm{AB},\\ \\mathrm{BC},\\ \\mathrm{CD},\\ \\mathrm{DA}$ の中点をそれぞれ $\\mathrm{K},\\ \\mathrm{L},\\ \\mathrm{M},\\ \\mathrm{N}$ とする．  \r\n(1) $4\\vec{\\mathrm{MK}}\\cdot\\vec{\\mathrm{LN}}=|\\vec{\\mathrm{AC}}|^2-|\\vec{\\mathrm{BD}}|^2$ を示せ．  \r\n(2) $|\\vec{\\mathrm{AC}}|=|\\vec{\\mathrm{BD}}|=\\sqrt{6},\\ |\\vec{\\mathrm{BC}}|=|\\vec{\\mathrm{AD}}|=\\sqrt{5},\\ |\\vec{\\mathrm{AB}}|=|\\vec{\\mathrm{CD}}|=\\sqrt{3}$ とする．辺 $\\mathrm{AC}$ の中点を $\\mathrm{P}$ とするとき，四面体 $\\mathrm{PKLN}$ の体積を求めよ．"
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 6・1\r\n\r\n座標空間に $3$ 点 $\\mathrm{A}(2,\\ 0,\\ 0),\\ \\mathrm{B}(2,\\ 2,\\ 0),\\ \\mathrm{C}(0,\\ 0,\\ 4)$ があり，$\\mathrm{A},\\ \\mathrm{B},\\ \\mathrm{C}$ を通る平面を $\\alpha$ とする．  \r\n(1) 三角形 $\\mathrm{ABC}$ の外心 $\\mathrm{P}$ の座標と外接円の半径を求めよ．  \r\n(2) $\\alpha$ と $\\mathrm{P}$ で接する半径が $5$ である球面の中心の座標を求めよ．\r\n\r\n## 6・2\r\n\r\n座標空間に $3$ 点 $\\mathrm{A}(1,\\ 1,\\ 2),\\ \\mathrm{B}(-1,\\ 1,\\ 2),\\ \\mathrm{C}(0,\\ 2,\\ 1)$ がある．点 $(2,\\ 3,\\ 3)$ を通り，ベクトル $(a,\\ 1,\\ 1)$ に平行な直線 $l$ が，三角形 $\\mathrm{ABC}$ の周または内部と共有点をもつような $a$ の値の範囲を求めよ．\r\n\r\n## 6・3\r\n\r\n$xyz$ 空間内の $3$ 点 $\\mathrm{O}(0,\\ 0,\\ 0),\\ \\mathrm{A}(1,\\ 0,\\ 0),\\ \\mathrm{B}(0,\\ 0,\\ 1)$ を頂点とする三角形 $\\mathrm{OAB}$ を，$z$ 軸のまわりに $1$ 回転させてできる円錐を $V$ とする．また，$x$ 軸を含み点 $(0,\\ 1,\\ 1)$ を通る平面を $\\alpha$ とする．  \r\n(1) $\\alpha$ の方程式を求めよ．  \r\n(2) $V$ の側面を表す方程式を求めよ．  \r\n(3) $\\alpha$ が $V$ によって切り取られる部分の面積を求めよ．"
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 7・1\r\n\r\n異なる複素数 $\\alpha,\\ \\beta,\\ \\gamma$ が $2\\alpha^2+\\beta^2+\\gamma^2-2\\alpha\\beta-2\\alpha\\gamma=0$ を満たすとき，次の問に答えよ．  \r\n(1) 複素数平面上で，$3$ 点 $\\mathrm{A}(\\alpha),\\ \\mathrm{B}(\\beta),\\ \\mathrm{C}(\\gamma)$ を頂点とする三角形 $\\mathrm{ABC}$ はどのような三角形か．  \r\n(2) $k$ は実数の定数とする．$\\alpha,\\ \\beta,\\ \\gamma$ が $x$ の $3$ 次方程式 $x^3+kx+20=0$ の解であるとき，$\\alpha,\\ \\beta,\\ \\gamma$ および $k$ を求めよ．\r\n\r\n## 7・2\r\n\r\n右の図のように三角形 $\\mathrm{ABC}$ があり，各辺の外側に正方形 $\\mathrm{ABEF},\\ \\mathrm{BCGH},\\ \\mathrm{CAIJ}$ を作る．  \r\n(1) 複素数平面上において，点 $\\mathrm{A},\\ \\mathrm{B},\\ \\mathrm{C}$ がそれぞれ複素数 $\\alpha,\\ \\beta,\\ \\gamma$ で表されているとき，点 $\\mathrm{F},\\ \\mathrm{H},\\ \\mathrm{J}$ を表す複素数を $\\alpha,\\ \\beta,\\ \\gamma$ の式で表せ．  \r\n(2) $3$ つの正方形 $\\mathrm{ABEF},\\ \\mathrm{BCGH},\\ \\mathrm{CAIJ}$ の中心をそれぞれ $\\mathrm{P},\\ \\mathrm{Q},\\ \\mathrm{R}$ とする．このとき線分 $\\mathrm{AQ}$ と線分 $\\mathrm{PR}$ は長さが等しく，$\\mathrm{AQ} \\perp \\mathrm{PR}$ であることを証明せよ．\r\n\r\n## 7・3\r\n\r\n$N$ を $3$ 以上の整数とし，虚数 $z=\\cos\\theta+i\\sin\\theta$ は $z^N=1$ を満たすとして，以下の数列の和 $S_1,\\ S_2,\\ S_3$ の値を求めよ．ただし，$i$ は虚数単位である．  \r\n(1) $S_1=1+z+z^2+\\cdots+z^{N-1}$  \r\n(2) $S_2=1+\\cos\\theta+\\cos 2\\theta+\\cdots+\\cos(N-1)\\theta$  \r\n(3) $S_3=1+\\cos^2\\theta+\\cos^2 2\\theta+\\cdots+\\cos^2(N-1)\\theta$"
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 8・1\r\n\r\n$z$ を $1$ でない複素数とし，$w=\\dfrac{z}{z-1}$ とおく．このとき，$|w| \\geqq \\sqrt{2}$ を満たす $z$ の全体を複素数平面上に図示せよ．\r\n\r\n## 8・2\r\n\r\n$0$ でない複素数 $z$ に対し，$w=\\dfrac{1}{z}$ によって $w$ を定める．また，$z,\\ w$ が表す複素数平面上の点をそれぞれ $\\mathrm{P}(z),\\ \\mathrm{Q}(w)$ とする．  \r\n(1) $\\mathrm{P}$ が右の図の線分 $\\mathrm{AB}$ 上を動くとき，$\\mathrm{Q}$ の軌跡を求め複素数平面上に図示せよ．  \r\n(2) $\\mathrm{P}$ が線分 $\\mathrm{AB}$ と，$\\mathrm{AB}$ を直径とする半円を合わせた右の図形上を動くとき，$\\mathrm{Q}$ の軌跡を求め複素数平面上に図示せよ．\r\n\r\n## 8・3\r\n\r\n$r,\\ \\theta$ を，$0<r<1,\\ 0<\\theta<\\pi$ を満たす実数とし，複素数平面上の点列 $\\mathrm{P}_n(z_n)\\ (n=0,\\ 1,\\ 2,\\ \\cdots)$ を次のように定める．まず，点 $\\mathrm{P}_0(z_0)\\ (z_0=0)$ は原点とし，ここから $x$ 軸（実軸）の正の向きに距離 $1$ だけ進んだ点を $\\mathrm{P}_1(z_1)$ とする．次に，進行方向を左に角 $\\theta$ だけ変えて距離 $r$ だけ進んだ点を $\\mathrm{P}_2(z_2)$ とする．さらに，進行方向を左に角 $\\theta$ だけ変えて距離 $r^2$ だけ進んだ点を $\\mathrm{P}_3(z_3)$ とする．以下同様にして，$n=3,\\ 4,\\ 5,\\ \\cdots$ に対しても，点 $\\mathrm{P}_{n-1}(z_{n-1})$ から点 $\\mathrm{P}_n(z_n)$ まで進んだら，進行方向を左に角 $\\theta$ だけ変えて距離 $r^n$ だけ進んだ点を $\\mathrm{P}_{n+1}(z_{n+1})$ とする．  \r\n$n \\longrightarrow \\infty$ のとき，点 $\\mathrm{P}_n(z_n)$ が限りなく近づく点を $\\mathrm{P}(z)$ とする．また，複素数 $\\alpha$ を\r\n$$\r\n\\alpha=r(\\cos\\theta+i\\sin\\theta)\\quad \\text{（$i$ は虚数単位）}\r\n$$\r\nで定める．  \r\n(1) $z$ を $\\alpha$ で表せ．  \r\n(2) $0<r<\\dfrac{1}{2},\\ 0<\\theta<\\dfrac{\\pi}{4}$ の範囲で $r,\\ \\theta$ が変化するとき，点 $\\mathrm{P}(z)$ の存在範囲を求めて図示せよ．"
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 9・1\r\n\r\n三角形 $\\mathrm{ABC}$ において，$\\angle\\mathrm{ABC}=60^\\circ$，$\\mathrm{B}$ の対辺の長さ $b$ は整数，他の $2$ 辺の長さ $a,\\ c$ はいずれも素数である．このとき，三角形 $\\mathrm{ABC}$ は正三角形であることを示せ．\r\n\r\n## 9・2\r\n\r\n(1) $13x+37y=1$ を満たす整数 $x,\\ y$ の組をすべて求めよ．  \r\n(2) $482$ 以上の整数はすべて $13x+37y$（$x,\\ y$ は正の整数）の形に表せることを示せ．\r\n\r\n## 9・3\r\n\r\n$m$ を $2015$ 以下の正の整数とする．${}_{2015}\\mathrm{C}_m$ が偶数となる最小の $m$ を求めよ．"
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 10・1\r\n\r\n$e$ を自然対数の底とする．$e^e$ に最も近い整数を求めよ．必要ならば次の近似値を用いよ．\r\n$$\r\ne=2.718,\\quad \\log_e 2=0.693,\\quad \\log_e 3=1.099,\\quad \\log_e 5=1.609\r\n$$\r\n\r\n## 10・2\r\n\r\n三角形 $\\mathrm{ABC}$ に対して，辺 $\\mathrm{AB}$ 上に点 $\\mathrm{P}$ を，辺 $\\mathrm{BC}$ 上に点 $\\mathrm{Q}$ を，辺 $\\mathrm{CA}$ 上に点 $\\mathrm{R}$ を，いずれも頂点と異なるようにとる．$3$ 点 $\\mathrm{P},\\ \\mathrm{Q},\\ \\mathrm{R}$ がそれぞれの辺上を独立にくまなく動くとき，三角形 $\\mathrm{PQR}$ の重心が動く範囲を図示せよ．\r\n\r\n## 10・3\r\n\r\n$xy$ 平面において，点 $\\mathrm{P}$ から放物線 $y=x^2$ に異なる $2$ 本の接線が引けるとき，その接点を $\\mathrm{Q},\\ \\mathrm{R}$ とする．$\\angle\\mathrm{QPR}=\\dfrac{\\pi}{4}$ であるような $\\mathrm{P}$ の軌跡を求め，図示せよ．"
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 11・1\r\n\r\n(1) $25!$ が $5^a$ で割り切れるような最大の自然数 $a$ を求めよ．  \r\n(2) $1000!$ を $10$ 進法で表すとき，末尾に続く $0$ の個数を求めよ．\r\n\r\n## 11・2\r\n\r\n$a$ を正の定数とする．原点 $\\mathrm{O}$ を極とし，$x$ 軸の正の部分を始線とする極座標において，極方程式 $r=a(1+\\cos\\theta)$ により表される曲線 $C$ を考える．  \r\n(1) 極座標が $\\left(\\dfrac{a}{2},\\ 0\\right)$ の点を中心とし半径が $\\dfrac{a}{2}$ である円 $S$ を極方程式で表せ．  \r\n(2) $\\mathrm{P}$ は $C$ 上の点で，$y$ 軸上にないものとする．直線 $\\mathrm{OP}$ と円 $S$ の $\\mathrm{O}$ 以外の交点を $\\mathrm{Q}$ とするとき，線分 $\\mathrm{PQ}$ の長さは一定であることを示せ．  \r\n(3) 点 $\\mathrm{P}$ が曲線 $C$ 上を動くとき，極座標が $(2a,\\ 0)$ の点と $\\mathrm{P}$ の距離の最大値を求めよ．\r\n\r\n## 11・3\r\n\r\n$\\mathrm{O}$ を原点とする $xyz$ 空間に $3$ 点 $\\mathrm{A}(-2,\\ -2,\\ 0),\\ \\mathrm{B}(6,\\ -2,\\ 0),\\ \\mathrm{C}(-2,\\ 4,\\ 0)$ をとり，$S\\colon x^2+y^2+(z-4)^2 \\leqq 4$ を考える．  \r\n(1) 三角形 $\\mathrm{ABC}$ の周または内部の点を $\\mathrm{P}$ とする．このとき，$\\alpha+\\beta+\\gamma=1$ となるような $3$ つの $0$ 以上の実数 $\\alpha,\\ \\beta,\\ \\gamma$ を用いて\r\n$$\r\n\\vec{\\mathrm{OP}}=\\alpha\\vec{\\mathrm{OA}}+\\beta\\vec{\\mathrm{OB}}+\\gamma\\vec{\\mathrm{OC}}\r\n$$\r\nと表されることを示せ．  \r\n(2) 点 $\\mathrm{P}$ が三角形 $\\mathrm{ABC}$ の周および内部を，点 $\\mathrm{Q}$ が $S$ 上を動くとき，線分 $\\mathrm{PQ}$ の中点 $\\mathrm{M}$ が動いてできる立体を $V$ とする．次に，同一直線上にない $3$ 点 $\\mathrm{A}',\\ \\mathrm{B}',\\ \\mathrm{C}'$ に対して，大きさが $1$ 以下のベクトル $\\vec{r}$ と $\\alpha+\\beta+\\gamma=1$ となるような $3$ つの $0$ 以上の実数 $\\alpha,\\ \\beta,\\ \\gamma$ を用いて\r\n$$\r\n\\vec{\\mathrm{OR}}=\\alpha\\vec{\\mathrm{OA}'}+\\beta\\vec{\\mathrm{OB}'}+\\gamma\\vec{\\mathrm{OC}'}+\\vec{r}\r\n$$\r\nと表される点 $\\mathrm{R}$ 全体のなす集合を $W$ とする．$V$ と $W$ が一致するような $3$ 点 $\\mathrm{A}',\\ \\mathrm{B}',\\ \\mathrm{C}'$ の座標を求めよ．"
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 12・1\r\n\r\n$2^{50}<2^n+\\left(\\dfrac{5}{2}\\right)^n$ を満たす最小の自然数 $n$ を求めよ．ただし，$0.301<\\log_{10} 2<0.3011$ である．\r\n\r\n## 12・2\r\n\r\n平面上に凸五角形 $\\mathrm{A}_1\\mathrm{A}_2\\mathrm{A}_3\\mathrm{A}_4\\mathrm{A}_5$ がある．  \r\n$5$ 点 $\\mathrm{A}_1,\\ \\mathrm{A}_2,\\ \\mathrm{A}_3,\\ \\mathrm{A}_4,\\ \\mathrm{A}_5$ のうちから，$3$ 点を任意に選ぶ．選んだ $3$ 点を頂点とする三角形の重心を $\\mathrm{G}$ とし，残りの $2$ 点を結ぶ線分の中点を $\\mathrm{M}$ とするとき，はじめの $3$ 点の選び方によらず線分 $\\mathrm{GM}$ 上にある定点が存在することを示せ．ただし，$\\mathrm{G}$ と $\\mathrm{M}$ が一致する場合は，その点を線分 $\\mathrm{GM}$ とみなす．\r\n\r\n## 12・3\r\n\r\n$xy$ 平面上に $\\mathrm{PQ}=4,\\ \\mathrm{PR}=\\mathrm{QR}=\\sqrt{5}$ の二等辺三角形 $\\mathrm{PQR}$ がある．点 $\\mathrm{P}$ を $x$ 軸の正の部分に，点 $\\mathrm{Q}$ を $y$ 軸の正の部分にとり，点 $\\mathrm{R}$ は直線 $\\mathrm{PQ}$ に関して原点 $\\mathrm{O}$ と反対側にくるようにとる．三角形 $\\mathrm{PQR}$ を可能な限り動かすとき，点 $\\mathrm{R}$ が描く軌跡を $F$ とする．  \r\n(1) $\\mathrm{R}$ の軌跡 $F$ を求めよ．  \r\n(2) $F$ を原点のまわりに $-\\theta\\ \\left(0 \\leqq \\theta \\leqq \\dfrac{\\pi}{2}\\right)$ 回転して得られる曲線を $G_\\theta$ とする．  \r\n$G_\\theta$ の方程式が $ax^2+by^2=1$（$a,\\ b$ は実数の定数）の形になるように角 $\\theta$ を定め，その $\\theta$ に対して曲線 $G_\\theta$ を求めて，図示せよ．"
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 13・1\r\n\r\n複素数 $a_n\\ (n=1,\\ 2,\\ 3,\\ \\cdots)$ を次のように定める．\r\n$$\r\na_1=1+i,\\quad a_{n+1}=\\dfrac{a_n}{2a_n-3}\\quad (n=1,\\ 2,\\ 3,\\ \\cdots).\r\n$$\r\nただし，$i$ は虚数単位である．このとき，次の問に答えよ．  \r\n(1) 複素数平面上の $3$ 点 $0,\\ a_1,\\ a_2$ を通る円の中心を表す複素数と半径を求めよ．  \r\n(2) すべての自然数 $n$ に対して，点 $a_n$ は (1) の円上にあることを示せ．\r\n\r\n## 13・2\r\n\r\n$\\mathrm{O}$ を原点とする $xy$ 平面上で，次の条件を満たす点 $\\mathrm{P}$ の存在範囲を図示せよ．  \r\n条件：$\\mathrm{P}$ は原点と異なり，かつ放物線 $y=x^2+4x$ 上に直線 $\\mathrm{OP}$ に関して対称な相異なる $2$ 点が存在する．\r\n\r\n## 13・3\r\n\r\n正の整数 $n$ の正の平方根 $\\sqrt{n}$ は整数ではなく，それを $10$ 進法で表すと，小数第 $1$ 位は $0$ であり，第 $2$ 位は $0$ 以外の数であるとする．  \r\n(1) このような $n$ の中で最小のものを求めよ．  \r\n(2) このような $n$ を小さいものから順に並べたとき，$10$ 番目にくるものを求めよ．"
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 14・1\r\n\r\n座標平面において，$x$ 座標，$y$ 座標がともに整数である点を格子点と呼ぶ．$4$ つの格子点 $\\mathrm{O}(0,\\ 0),\\ \\mathrm{A}(a,\\ b),\\ \\mathrm{B}(a+c,\\ b+d),\\ \\mathrm{C}(c,\\ d)$ を頂点とする平行四辺形 $\\mathrm{OABC}$ の内部を $D$ とする．  \r\n(1) $ad-bc=1$ のとき，$D$ には格子点は存在しないことを示せ．  \r\n(2) $ad-bc=2$ のとき，$D$ に格子点があれば，それは平行四辺形 $\\mathrm{OABC}$ の対角線の交点であることを示せ．\r\n\r\n## 14・2\r\n\r\n自然数 $n$ に対して，$n$ の正の約数の総和を $S(n)$ で表す．例えば，\r\n$$\r\nS(18)=1+2+3+6+9+18=39\r\n$$\r\nである．以下，$n$ を正の偶数として，$n=2^a m$（$a$ は自然数，$m$ は正の奇数）と表す．  \r\n(1) $\\dfrac{S(n)}{S(m)}$ を $a$ の式で表せ．  \r\n(2) $S(n)=2n$ のとき，$S(m)-m$ を $a$ と $m$ の式で表せ．  \r\n(3) $S(n)=2n$ のとき，$m$ は素数で，かつ $m=2^{a+1}-1$ となることを示せ．\r\n\r\n## 14・3\r\n\r\n複素数平面上で，三角形 $\\mathrm{ABC}$ の頂点を表す複素数を $\\alpha,\\ \\beta,\\ \\gamma$ とし，次の $3$ つの条件を満たすとする．  \r\n（ア） 三角形 $\\mathrm{ABC}$ は一辺の長さが $\\sqrt{3}$ の正三角形である．  \r\n（イ） $\\alpha+\\beta+\\gamma=3$．  \r\n（ウ） $\\alpha\\beta\\gamma$ は，絶対値が $1$ で虚部は正である．  \r\nこのとき，次の問に答えよ．  \r\n(1) $z=\\alpha-1$ とおく．条件（ア）と（イ）より，$\\beta$ と $\\gamma$ を $z$ を用いて表せ．  \r\n(2) $\\arg\\alpha,\\ \\arg\\beta,\\ \\arg\\gamma$ を求めよ．ただし，$0^\\circ \\leqq \\arg\\alpha \\leqq \\arg\\beta \\leqq \\arg\\gamma < 360^\\circ$ とする．"
      }
    }
  },
  "math3": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 1・1\r\n\r\n三角形 $\\mathrm{ABC}$ の内角 $\\angle\\mathrm{A},\\ \\angle\\mathrm{B}$ の大きさ $A,\\ B$ が\r\n$$\r\n\\sin(3A+B) = \\sin 3A + \\sin B, \\quad \\cos(3A-B) = \\cos 3A - \\cos B\r\n$$\r\nをともに満たすとする．このとき，$A,\\ B$ を求めよ．\r\n\r\n## 1・2\r\n\r\n$1$ 辺の長さ $a$ の正三角形 $\\mathrm{ABC}$ とその外接円がある．外接円上で弧 $\\mathrm{BAC}$ 上にない点 $\\mathrm{P}$ をとり，$\\angle\\mathrm{BAP}=\\theta\\ \\left(0<\\theta<\\dfrac{\\pi}{3}\\right)$ とする．  \r\n(1) $\\mathrm{AP}=\\mathrm{BP}+\\mathrm{CP}$ が成り立つことを証明せよ．  \r\n(2) $\\mathrm{AP}^2+\\mathrm{BP}^2+\\mathrm{CP}^2$ の値が一定であることを示し，その値を求めよ．\r\n\r\n## 1・3\r\n\r\n$a,\\ b$ を $0$ でない実数の定数とする．区間 $\\left[0,\\ \\dfrac{\\pi}{2}\\right]$ の任意の $x$ に対して，\r\n$$\r\n-1 \\leqq a\\cos x + b\\sin x \\leqq 1\r\n$$\r\nが成り立つための必要十分条件を $a,\\ b$ を用いて表せ．"
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 2・1\r\n\r\n$t$ は実数の定数とする．$t \\leqq x \\leqq t+1$ における $3$ 次関数 $f(x)=x^3-6x^2+9x+2$ の最大値を $t$ を用いて表せ．\r\n\r\n## 2・2\r\n\r\n曲線 $C \\colon y=x^4-2x^3-3x^2+5x$ と直線 $l$ が異なる $2$ 点で接している．  \r\n(1) $l$ の方程式を求めよ．  \r\n(2) $C$ と $l$ で囲まれる図形の面積を求めよ．\r\n\r\n## 2・3\r\n\r\n$a$ を正の定数とする．座標平面上で曲線 $y=a(x^3-x)$ を考える．原点を中心とする円で，この曲線と相異なる $6$ 点で交わるものが存在するような $a$ の値の範囲を求めよ．"
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 3・1\r\n\r\nすべての実数 $x$ に対して定義された微分可能な関数 $f(x)$ があり，$\\lim\\limits_{x \\to \\infty}\\dfrac{f(x)}{x}=1$ を満たすとする．  \r\n(1) $e^x \\geqq 1+x+\\dfrac{x^2}{2}\\ （x \\geqq 0）$ を示せ．  \r\n(2) $\\lim\\limits_{x \\to \\infty} f(x)e^{-x}=0$ を示せ．  \r\n(3) $\\lim\\limits_{t \\to \\infty}\\displaystyle\\int_0^t \\{f(x)-f'(x)\\}e^{-x}\\,dx = f(0)$ を示せ．\r\n\r\n## 3・2\r\n\r\n関数 $f(x)$ を $f(x)=\\dfrac{1}{2}x\\{1+e^{-2(x-1)}\\}$ とする．ただし，$e$ は自然対数の底である．  \r\n(1) $x>\\dfrac{1}{2}$ ならば $0 \\leqq f'(x)<\\dfrac{1}{2}$ であることを示せ．  \r\n(2) $x_0$ を $x_0>\\dfrac{1}{2}$ とし，数列 $\\{x_n\\}$ を，$x_{n+1}=f(x_n)\\ (n=0,\\ 1,\\ 2,\\ \\cdots)$ によって定める．このとき，$\\lim\\limits_{n \\to \\infty}x_n=1$ であることを示せ．\r\n\r\n## 3・3\r\n\r\n$a$ は $0<a<\\pi$ を満たす定数とする．$n=0,\\ 1,\\ 2,\\ \\cdots$ に対し，$n\\pi<x<(n+1)\\pi$ の範囲に\r\n$$\r\n\\sin(x+a)=x\\sin x\r\n$$\r\nを満たす $x$ がただ $1$ つ存在するので，この $x$ の値を $x_n$ とする．  \r\n(1) 極限値 $\\lim\\limits_{n \\to \\infty}(x_n-n\\pi)$ を求めよ．  \r\n(2) 極限値 $\\lim\\limits_{n \\to \\infty}n(x_n-n\\pi)$ を求めよ．"
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 4・1\r\n\r\n$x>0$ のとき，任意の自然数 $n$ に対して\r\n$$\r\n1+\\dfrac{x}{1!}+\\dfrac{x^2}{2!}+\\dfrac{x^3}{3!}+\\cdots+\\dfrac{x^{n-1}}{(n-1)!}>\\left(1-\\dfrac{x^n}{n!}\\right)e^x\r\n$$\r\nが成り立つことを証明せよ．ただし，$e$ は自然対数の底とする．\r\n\r\n## 4・2\r\n\r\n$\\alpha$ を $0<\\alpha<1$ を満たす定数とする．曲線 $C \\colon x^{\\alpha}+y^{\\alpha}=1\\ (x>0,\\ y>0)$ 上の点 $\\mathrm{P}$ における $C$ の接線が $x$ 軸，$y$ 軸と交わる点をそれぞれ $\\mathrm{A},\\ \\mathrm{B}$ とする．線分 $\\mathrm{AB}$ の長さが $\\mathrm{P}$ の位置によらず一定となるように $\\alpha$ の値を定めよ．\r\n\r\n## 4・3\r\n\r\n$n$ を正の整数とする．以下の問いに答えよ．  \r\n(1) $p,\\ q,\\ r,\\ s$ を定数とする．\r\n$$\r\np\\log x+q=r\\log x+s\r\n$$\r\nがすべての正の実数 $x$ で成り立つとき，\r\n$$\r\np=r \\quad \\text{かつ} \\quad q=s\r\n$$\r\nであることを示せ．  \r\n(2) $\\dfrac{d^n}{dx^n}(x^n\\log x)=a_n\\log x+b_n\\ （a_n,\\ b_n \\text{ は } x \\text{ によらない数}）$ と表されることを証明せよ．  \r\n(3) (2) の $a_n,\\ b_n$ のそれぞれに関する漸化式を求め，$a_n,\\ b_n$ を $n$ を用いた式で表せ．ただし，$1+\\dfrac{1}{2}+\\dfrac{1}{3}+\\cdots+\\dfrac{1}{n}$ のような，これ以上簡単にできない数列の和が現れた場合は，そのままの形で表せばよい．"
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 5・1\r\n\r\n(1) $y=\\dfrac{x\\cos x}{\\sin x}$ は $0<x<\\pi$ の範囲で単調に減少することを示せ．  \r\n(2) $\\dfrac{1}{\\pi}<x<\\pi$ において，$f(x)=\\sin x\\cdot\\sin\\dfrac{1}{x}$ が極大となる $x$ の値を求めよ．\r\n\r\n## 5・2\r\n\r\n$t$ を実数の定数として，$xy$ 平面上の直線 $l_t \\colon y=-tx+e^t$ を考える．$t$ が実数全体を変化するとき，$l_t$ が通過する範囲を図示せよ．ただし，必要ならば，$\\lim\\limits_{x \\to +0}x\\log x=0$ を用いてよい．\r\n\r\n## 5・3\r\n\r\n$f(x)$ はすべての実数 $x$ において微分可能で，関係式\r\n$$\r\nf(2x)=(e^x+1)f(x)\r\n$$\r\nを満たしている．  \r\n(1) $f(0)$ を求めよ．  \r\n(2) $x \\neq 0$ に対して，\r\n$$\r\n\\dfrac{f(x)}{e^x-1}=\\dfrac{f\\left(\\dfrac{x}{2}\\right)}{e^{\\frac{x}{2}}-1}\r\n$$\r\nが成り立つことを示せ．  \r\n(3) $f'(0)=\\lim\\limits_{h \\to 0}\\dfrac{f(h)}{e^h-1}$ が成り立つことを示せ．  \r\n(4) $f(x)=(e^x-1)f'(0)$ が成り立つことを示せ．"
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 6・1\r\n\r\n半径 $1$ の半円の弧を $n$ 等分する．ただし，$n$ は $2$ 以上の自然数である．半円の弧の端の $1$ つを $\\mathrm{P}_0$ とし，$n$ 等分点を $\\mathrm{P}_0$ から近い順に $\\mathrm{P}_1,\\ \\mathrm{P}_2,\\ \\mathrm{P}_3,\\ \\cdots,\\ \\mathrm{P}_{n-1}$ とする．  \r\n$1 \\leqq k \\leqq n-1$ である整数 $k$ に対して，弧 $\\mathrm{P}_0\\mathrm{P}_k$ と線分 $\\mathrm{P}_0\\mathrm{P}_k$ で囲まれた部分の面積を $S_k$ とする．このとき，$\\lim\\limits_{n \\to \\infty}\\dfrac{1}{n^3}\\sum\\limits_{k=1}^{n-1}kS_k$ を求めよ．\r\n\r\n## 6・2\r\n\r\n(1) 連続関数 $f(x)$ について，\r\n$$\r\n\\int_0^x tf(x-t)\\,dt=x\\int_0^x f(u)\\,du-\\int_0^x uf(u)\\,du\r\n$$\r\nが成り立つことを示せ．  \r\n(2) すべての実数 $x$ に対して，\r\n$$\r\n\\int_0^x tf(x-t)\\,dt=\\int_0^x f(t)\\,dt+2x\r\n$$\r\nを満たす連続関数 $f(x)$ がある．$g(x)=e^{-x}f(x)$ とおくとき，$g'(x)$ を求めよ．さらに，$f(x)$ を求めよ．\r\n\r\n## 6・3\r\n\r\n$0 \\leqq x<1$ において，関数 $f(x)$ を\r\n$$\r\nf(x)=\\int_0^x \\dfrac{1}{\\sqrt{1-t^2}}\\,dt\r\n$$\r\nと定める．  \r\n(1) 曲線 $C \\colon y=f(x)$ の点 $\\left(\\dfrac{1}{2},\\ f\\left(\\dfrac{1}{2}\\right)\\right)$ における接線 $l$ の方程式を求めよ．  \r\n(2) (1) の $C$ と $l$ と $x$ 軸とで囲まれる図形の面積を求めよ．"
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 7・1\r\n\r\n$n$ を $2$ 以上の整数，$k$ を正の整数とするとき，次の各不等式を証明せよ．  \r\n(1) $(k-1)^n < \\displaystyle\\int_{k-1}^k x^n\\,dx < \\dfrac{1}{2}\\{(k-1)^n+k^n\\}$  \r\n(2) $\\dfrac{3n+1}{2n+2}<\\left(\\dfrac{1}{n}\\right)^n+\\left(\\dfrac{2}{n}\\right)^n+\\left(\\dfrac{3}{n}\\right)^n+\\cdots+\\left(\\dfrac{n}{n}\\right)^n<\\dfrac{2n+1}{n+1}$\r\n\r\n## 7・2\r\n\r\n$\\lim\\limits_{n \\to \\infty}\\displaystyle\\int_0^{\\pi} x^2|\\sin nx|\\,dx$ を求めよ．ただし，$n$ は自然数とする．\r\n\r\n## 7・3\r\n\r\n数列 $\\{a_n\\}$ を\r\n$$\r\na_n=\\int_0^1 (\\sqrt{1-x^2})^n\\,dx \\quad (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nと定義するとき，  \r\n(1) $a_{n+2}$ と $a_n$ の関係式を求めよ．  \r\n(2) $(n+2)a_{n+1}a_n=\\dfrac{\\pi}{2}\\ (n=1,\\ 2,\\ 3,\\ \\cdots)$ を示せ．  \r\n(3) $a_n>a_{n+1}\\ (n=1,\\ 2,\\ 3,\\ \\cdots)$ を示し，$\\lim\\limits_{n \\to \\infty}\\sqrt{n}\\,a_n$ を求めよ．"
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 8・1\r\n\r\n次の条件 (イ)，(ロ) を満たす関数 $f(x)$ を求めよ．  \r\n(イ) $f\\left(\\dfrac{\\pi}{2}\\right)=1$  \r\n(ロ) $f'(x)=\\cos x+\\left\\{\\displaystyle\\int_0^{\\pi}|f(t)|\\,dt\\right\\}\\sin x$\r\n\r\n## 8・2\r\n\r\n座標平面において，方程式\r\n$$\r\n(x^2+y^2)^2=2xy\r\n$$\r\nの表す曲線 $C$ を考える．  \r\n(1) 原点を極，$x$ 軸の正の部分を始線とする極座標で，$C$ 上の原点以外の点を $(r,\\ \\theta)\\ (r>0)$ と表すとき，$r$ を $\\theta$ を用いて表せ．  \r\n(2) $C$ で囲まれた $2$ つの部分の面積の和を求めよ．\r\n\r\n## 8・3\r\n\r\n$\\mathrm{O}$ を原点とする座標平面上に $2$ 点 $\\mathrm{A}(0,\\ 1),\\ \\mathrm{B}(0,\\ 2)$ をとる．線分 $\\mathrm{OB}$ を直径とし，点 $(1,\\ 1)$ を通る半円を $\\varGamma$ とする．長さ $\\pi$ の糸の一端を $\\mathrm{O}$ に固定して $\\varGamma$ に巻き付けてある．この糸の他端 $\\mathrm{P}$ を引き，それが $x$ 軸に到達するまで，ゆるむことなくほどいていく．  \r\n図のように，糸と半円との接点を $\\mathrm{Q}$ とし，$\\angle\\mathrm{BAQ}$ の大きさを $t$ とする．  \r\n(1) $\\vec{\\mathrm{OP}}$ を $t$ を用いて表せ．  \r\n(2) $\\mathrm{P}$ が描く曲線の長さを求めよ．  \r\n(3) $\\mathrm{P}$ が描く曲線と，$x$ 軸および $y$ 軸で囲まれた図形の面積を求めよ．"
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 9・1\r\n\r\n曲線 $y=x\\sqrt{1-x^2}\\ (-1 \\leqq x \\leqq 1)$ と $x$ 軸とで囲まれた図形を $y$ 軸の周りに $1$ 回転してできる立体の体積を求めよ．\r\n\r\n## 9・2\r\n\r\n$xy$ 平面において，曲線 $y=1-x^2$ と，直線 $l \\colon x+y=1$ とで囲まれた部分を $D$ とする．$l$ の周りに $D$ を $1$ 回転してできる立体の体積を求めよ．\r\n\r\n## 9・3\r\n\r\n$xyz$ 空間内の $3$ 点 $\\mathrm{A}(1,\\ 0,\\ 0),\\ \\mathrm{B}(0,\\ 1,\\ 0),\\ \\mathrm{C}(0,\\ 0,\\ 1)$ を通る平面を $\\alpha$ とする．この $\\alpha$ に関して原点と同じ側にあり，$x \\geqq 0,\\ z \\geqq 0,\\ x^2+y^2 \\leqq r^2$ を満たす点全体からなる立体を $K$ とする．ただし，$r$ は $0<r<\\dfrac{1}{\\sqrt{2}}$ を満たす定数であるとする．  \r\nこのとき，$K$ の体積を求めよ．"
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 10・1\r\n\r\n四角形 $\\mathrm{ABCD}$ の $4$ つの内角を $A,\\ B,\\ C,\\ D$ で表すとき\r\n$$\r\n\\sin A + \\sin B = \\sin C + \\sin D\r\n$$\r\nが成り立つ四角形 $\\mathrm{ABCD}$ は，どのような四角形か．\r\n\r\n## 10・2\r\n\r\n$xy$ 平面において，曲線 $y=e^x$ 上を動く点 $\\mathrm{P}$ の時刻 $t$ における座標を $(x,\\ y)$ と表し，$\\mathrm{P}$ の速度ベクトルと加速度ベクトルをそれぞれ $\\vec{v}=\\left(\\dfrac{dx}{dt},\\ \\dfrac{dy}{dt}\\right)$ と $\\vec{\\alpha}=\\left(\\dfrac{d^2x}{dt^2},\\ \\dfrac{d^2y}{dt^2}\\right)$ とする．すべての時刻 $t$ で $|\\vec{v}|=1$ かつ $\\dfrac{dx}{dt}>0$ であるとして，次の問に答えよ．  \r\n(1) $\\mathrm{P}$ が点 $(s,\\ e^s)$ を通過する時刻における速度ベクトル $\\vec{v}$ を $s$ を用いて表せ．  \r\n(2) $\\mathrm{P}$ が点 $(s,\\ e^s)$ を通過する時刻における加速度ベクトル $\\vec{\\alpha}$ を $s$ を用いて表せ．  \r\n(3) $\\mathrm{P}$ が曲線全体を動くとき，$|\\vec{\\alpha}|$ の最大値を求めよ．\r\n\r\n## 10・3\r\n\r\n平面上に一辺の長さが $2$ の正方形 $\\mathrm{ABCD}$ があり対角線の交点を $\\mathrm{O}$ とする．この平面上で，$\\mathrm{O}$ を中心とする角 $\\theta$ の回転移動によって，$4$ 点 $\\mathrm{A},\\ \\mathrm{B},\\ \\mathrm{C},\\ \\mathrm{D}$ はそれぞれ $\\mathrm{A}',\\ \\mathrm{B}',\\ \\mathrm{C}',\\ \\mathrm{D}'$ に移るとする．また，$2$ つの正方形 $\\mathrm{ABCD}$ と $\\mathrm{A}'\\mathrm{B}'\\mathrm{C}'\\mathrm{D}'$ の重なる部分の面積を $S$ とする．  \r\n角 $\\theta$ が $0<\\theta<\\dfrac{\\pi}{2}$ の範囲を動くとき，面積 $S$ の最小値を求めよ．"
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 11・1\r\n\r\n(1) $x>0$ のとき，不等式\r\n$$\r\nx-\\dfrac{x^2}{2}<\\log(1+x)<x\r\n$$\r\nが成り立つことを証明せよ．  \r\n(2) $2$ 以上の自然数 $n$ に対して，\r\n$$\r\na_n=\\left(1+\\dfrac{1}{n^2}\\right)\\left(1+\\dfrac{2}{n^2}\\right)\\left(1+\\dfrac{3}{n^2}\\right)\\cdots\\left(1+\\dfrac{n-1}{n^2}\\right)\r\n$$\r\nとおく．$\\lim\\limits_{n \\to \\infty}a_n$ を求めよ．\r\n\r\n## 11・2\r\n\r\n中心角 $\\theta\\ (0<\\theta<2\\pi)$ の扇形があり，その弧と，弧の両端を結ぶ線分で囲まれる領域がある．この領域の面積を一定に保って扇形の半径と中心角が変化するとき，扇形の弧長を最小にする $\\theta$ の値を求めよ．\r\n\r\n## 11・3\r\n\r\n$xyz$ 空間に，$2$ つの立体\r\n$$\r\nK_1 \\colon \\begin{cases} -\\dfrac{\\pi}{2} \\leqq x \\leqq \\dfrac{\\pi}{2} \\\\ 0 \\leqq z \\leqq \\cos x \\end{cases}, \\quad K_2 \\colon \\begin{cases} -\\dfrac{\\pi}{2} \\leqq y \\leqq \\dfrac{\\pi}{2} \\\\ 0 \\leqq z \\leqq \\cos y \\end{cases}\r\n$$\r\nがある．$K_1$ と $K_2$ の共通部分を $K$ とする．  \r\n(1) 平面 $z=\\dfrac{1}{\\sqrt{2}}$ による $K$ の切り口の面積を求めよ．  \r\n(2) $K$ の体積を求めよ．"
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 12・1\r\n\r\n(1) $\\cos 5\\theta=f(\\cos\\theta)$ を満たす多項式 $f(x)$ を $1$ つ求めよ．  \r\n(2) $\\cos\\dfrac{\\pi}{10}\\cos\\dfrac{3\\pi}{10}\\cos\\dfrac{7\\pi}{10}\\cos\\dfrac{9\\pi}{10}=\\dfrac{5}{16}$ を示せ．\r\n\r\n## 12・2\r\n\r\n$l$ は $3$ 以上の整数の定数とする．  \r\n$1$ と書かれたカードが $1$ 枚，$2$ と書かれたカードが $1$ 枚，$\\cdots$，$n$ と書かれたカードが $1$ 枚，合計 $n$ 枚のカードの入った箱がある．この箱の中から，$1$ 枚のカードを無作為に取り出して書かれた数を記録し箱に戻すことを $l$ 回繰り返す．このとき，記録された数の最大値，最小値について考える．  \r\n(1) $k$ は $1 \\leqq k \\leqq n$ を満たす整数とする．$1$ 回目に最小値が，$l$ 回目に最大値が記録され，かつその差が $k-1$ となる確率を $n,\\ k,\\ l$ を用いて表せ．  \r\n(2) $1$ 回目に最小値が，$l$ 回目に最大値が記録される確率を $p_n$ とするとき，$\\lim\\limits_{n \\to \\infty}p_n$ を求めよ．\r\n\r\n## 12・3\r\n\r\n$x_i\\ (i=1,\\ 2,\\ 3,\\ \\cdots,\\ n)$ を正の数とし，$\\sum\\limits_{i=1}^n x_i=a$ とおく．このとき，不等式\r\n$$\r\n\\sum_{i=1}^n x_i\\log x_i \\geqq a\\log\\dfrac{a}{n}\r\n$$\r\nが成り立つことを証明せよ．ただし，$n$ は正の整数である．"
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 13・1\r\n\r\n$n$ は $3$ 以上の整数とし，周の長さが $1$ の正 $n$ 角形の面積を $S_n$ とする．  \r\n(1) この正 $n$ 角形の外接円の半径を $n$ を用いて表せ．  \r\n(2) $S_n$ を $n$ を用いて表し，$\\lim\\limits_{n \\to \\infty}S_n$ を求めよ．  \r\n(3) $S_n<S_{n+1}$ を証明せよ．\r\n\r\n## 13・2\r\n\r\n一辺の長さが $1$ の正方形の辺上を点 $\\mathrm{P}$ が $1$ 周するとき，$\\mathrm{P}$ を中心とする半径が $1$ の球（内部も含む）が通過する領域の体積を求めよ．\r\n\r\n## 13・3\r\n\r\n数列 $\\{a_n\\}$ は次の式で与えられている．\r\n$$\r\na_0=\\int_0^1 e^{-x}\\,dx, \\quad a_n=\\dfrac{1}{n!}\\int_0^1 x^n e^{-x}\\,dx \\quad (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nただし，$e$ は自然対数の底である．このとき，次の各問に答えよ．  \r\n(1) $a_n=a_{n-1}-\\dfrac{1}{n!\\,e}\\ (n=1,\\ 2,\\ 3,\\ \\cdots)$ が成り立つことを示せ．  \r\n(2) $0<a_n<\\dfrac{1}{n!\\,e}\\ (n=1,\\ 2,\\ 3,\\ \\cdots)$ が成り立つことを示せ．さらに，\r\n$$\r\n0<n!\\left(e-\\sum_{k=0}^n \\dfrac{1}{k!}\\right)<1 \\quad (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nが成り立つことを示せ．  \r\n(3) 実数 $e$ が無理数であることを示せ．"
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 14・1\r\n\r\n$n$ を正の整数とする．$a_n=\\sum\\limits_{k=1}^n \\dfrac{1}{\\sqrt{k}}$，$b_n=\\sum\\limits_{k=1}^n \\dfrac{1}{\\sqrt{2k+1}}$ とするとき，$\\lim\\limits_{n \\to \\infty}a_n$，$\\lim\\limits_{n \\to \\infty}\\dfrac{b_n}{a_n}$ を求めよ．\r\n\r\n## 14・2\r\n\r\n座標平面の曲線 $C \\colon y=\\dfrac{1}{2}(e^x+e^{-x})$ 上に定点 $\\mathrm{A}(0,\\ 1)$ がある．$C$ 上の点 $\\mathrm{P}(s,\\ t)\\ (s>0)$ に対し，$\\mathrm{P}$ における $C$ の接線 $l$ 上の点 $\\mathrm{Q}(X,\\ Y)$ を $\\mathrm{PQ}=\\overgroup{\\mathrm{AP}},\\ X<s$ となるように定める．ただし，$\\overgroup{\\mathrm{AP}}$ は，曲線 $C$ の $\\mathrm{A}$ から $\\mathrm{P}$ までの部分の長さを表す．  \r\n(1) $X,\\ Y$ を $s$ を用いて表せ．  \r\n(2) $s$ が正の実数全体を変化するときの $\\mathrm{Q}$ の軌跡を $K$ とする．$\\mathrm{Q}$ における $K$ の接線を $L$ とし，$\\mathrm{P}$ から $x$ 軸へ垂線 $\\mathrm{PH}$ を下ろす．このとき $\\mathrm{H}$ は $L$ 上にあること，および $\\mathrm{QH}=1$ が成り立つことを示せ．\r\n\r\n## 14・3\r\n\r\n$xyz$ 空間に，原点 $\\mathrm{O}$ を中心とする半径が $1$ の球 $G$（内部も含む）がある．また，放物線 $y=1-x^2,\\ z=0$ を $z$ 軸方向に平行移動して得られる曲面によって $xyz$ 空間を $2$ つに分割したとき，$\\mathrm{O}$ を含まない方を $T$ とする．$G$ と $T$ の共通部分の体積を求めよ．"
      }
    }
  },
  "science_math": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 1・1\r\n\r\n$xy$ 平面上で曲線 $C\\colon y=x^2$（$x>0$）上の点 $\\mathrm{P}$ を中心とし，$x$ 軸に接する円を考える．$\\mathrm{P}$ が $C$ 上を動くとき，この円の内部が動く範囲を図示せよ．\r\n\r\n## 1・2\r\n\r\n点 $\\mathrm{P}$ は右の図の頂点 $\\mathrm{A},\\ \\mathrm{B},\\ \\mathrm{C},\\ \\mathrm{D},\\ \\mathrm{E},\\ \\mathrm{F}$ を次の規則に従って動く．  \r\n(I) $\\mathrm{P}$ は時刻 $0$ で $\\mathrm{A}$ にいる．  \r\n(II) $\\mathrm{P}$ が時刻 $n$（$n=0,\\ 1,\\ 2,\\ 3,\\ \\cdots$）にある頂点 $\\mathrm{X}$ にいるとすると，時刻 $n+1$ には，$\\mathrm{P}$ は $\\mathrm{X}$ と隣接する頂点の $1$ つに同じ確率でいる（たとえば，$\\mathrm{X}$ が $\\mathrm{D}$ のとき，時刻 $n+1$ には $\\mathrm{P}$ は確率 $\\dfrac{1}{3}$ で $\\mathrm{A},\\ \\mathrm{C},\\ \\mathrm{E}$ のいずれかにいる）．  \r\n$\\mathrm{P}$ が時刻 $n$ に $\\mathrm{A}$ にいる確率を求めよ．\r\n\r\n## 1・3\r\n\r\n$xyz$ 空間において，条件 $x^2+y^2\\leqq z^2,\\ z^2\\leqq x,\\ 0\\leqq z\\leqq 1$ をすべて満たす点 $\\mathrm{P}(x,\\ y,\\ z)$ の全体からなる立体を考える．この立体の体積 $V$ を求めよ．"
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 2・1\r\n\r\n三角形 $\\mathrm{ABC}$ において，$\\tan A,\\ \\tan B,\\ \\tan C$ の値がすべて整数であるとき，それらの値を求めよ．\r\n\r\n## 2・2\r\n\r\n$a$ を $1$ 以上の実数，$b$ を正の実数とする．  \r\n(1) $0$ 以上のすべての実数 $x$ について，不等式 $e^x-a(x+2b)\\geqq 0$ が成り立つための，$a,\\ b$ の満たすべき条件を求めよ．ただし，$e$ は自然対数の底とする．  \r\n(2) $a,\\ b$ が (1) で求めた範囲を動くとき，定積分\r\n$$\r\n\\dfrac{1}{ae^b}\\int_0^1 \\dfrac{1}{x+2b}\\,dx\r\n$$\r\nの値を最小にする $a,\\ b$ と，その最小値を求めよ．\r\n\r\n## 2・3\r\n\r\n関数 $f_n(x)$（$n=0,\\ 1,\\ 2,\\ \\cdots$）は次の条件を満たしている．\r\n$$\r\n\\begin{cases}\r\nf_0(x)=1,\\ f_1(x)=\\cos x \\\\\r\n2f_n(x)\\cos x=f_{n-1}(x)+f_{n+1}(x) \\quad (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n\\end{cases}\r\n$$\r\n(1) $f_n(x)$ を求めよ．  \r\n(2) 極限値 $\\lim\\limits_{n\\to\\infty}\\displaystyle\\int_0^1 \\dfrac{\\{f_n(x)\\}^2}{1+x^2}\\,dx$ を求めよ．"
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 3・1\r\n\r\n$y=e^{-x}$ と $y=ax+3$（$a<0$）のグラフが囲む図形の面積を最小にする $a$ の値を求めよ．\r\n\r\n## 3・2\r\n\r\n実数 $x$ に対し，$x$ 以上の最小の整数を $f(x)$ とする．$a,\\ b$ を正の実数とするとき，極限\r\n$$\r\n\\lim_{x\\to\\infty} x^c \\left(\\dfrac{1}{f(ax-7)}-\\dfrac{1}{f(bx+3)}\\right)\r\n$$\r\nが収束するような実数 $c$ の最大値と，そのときの極限値を求めよ．\r\n\r\n## 3・3\r\n\r\n$a$ を正の数，$b$ を実数とし，\r\n$$\r\nf(x)=\\log x(1-x)-ax(1-x)+b \\quad (0<x<1)\r\n$$\r\nとおく．  \r\n(1) $f(x)$ の区間 $0<x<1$ における最大値を求めよ．  \r\n(2) $f(x)=0$ が区間 $0<x<1$ において相異なる $4$ 個の解をもつために，$a,\\ b$ が満たすべき条件を求めよ．また，この条件を満たす点 $(a,\\ b)$ の集合を $ab$ 平面上に図示せよ．"
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 5・1\r\n\r\n$a$ を正の定数とする．原点を $\\mathrm{O}$ とする座標平面上に定点 $\\mathrm{A}=\\mathrm{A}(a,\\ 0)$ と，$\\mathrm{A}$ と異なる動点 $\\mathrm{P}=\\mathrm{P}(x,\\ y)$ をとる．次の条件\r\n$$\r\n\\text{A から P に向けた半直線上の点 Q に対し}\r\n$$\r\n$$\r\n\\dfrac{\\mathrm{AQ}}{\\mathrm{AP}}\\leqq 2 \\text{ ならば } \\dfrac{\\mathrm{QP}}{\\mathrm{OQ}}\\leqq \\dfrac{\\mathrm{AP}}{\\mathrm{OA}}\r\n$$\r\nを満たす $\\mathrm{P}$ からなる領域を $D$ とする．$D$ を図示せよ．\r\n\r\n## 5・2\r\n\r\n自然数 $n$ に対して，方程式 $(1+x)^n=1+2^n x$ の実数解の個数を求めよ．\r\n\r\n## 5・3\r\n\r\n$n$ を $2$ 以上の整数とする．自然数（$1$ 以上の整数）の $n$ 乗になる数を $n$ 乗数と呼ぶことにする．以下の問に答えよ．  \r\n(1) 連続する $2$ 個の自然数の積は $n$ 乗数でないことを示せ．  \r\n(2) 連続する $n$ 個の自然数の積は $n$ 乗数でないことを示せ．"
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 6・1\r\n\r\n自然数 $n$ に対して，和\r\n$$\r\nS_n=1+\\dfrac{1}{2}+\\dfrac{1}{3}+\\dots+\\dfrac{1}{n}\r\n$$\r\nを考える．  \r\n(1) 各自然数 $n$ に対して $2^k\\leqq n$ を満たす最大の整数 $k$ を $f(n)$ で表すとき，$2$ つの奇数 $a_n,\\ b_n$ が存在して\r\n$$\r\nS_n=\\dfrac{a_n}{2^{f(n)}b_n}\r\n$$\r\nと表されることを示せ．  \r\n(2) $n\\geqq 2$ のとき $S_n$ は整数にならないことを示せ．  \r\n(3) さらに，自然数 $m,\\ n$（$m<n$）に対して，和\r\n$$\r\nS_{m,\\,n}=\\dfrac{1}{m}+\\dfrac{1}{m+1}+\\dots+\\dfrac{1}{n}\r\n$$\r\nを考える．$S_{m,\\,n}$ はどんな $m,\\ n$（$m<n$）に対しても整数にならないことを示せ．\r\n\r\n## 6・2\r\n\r\n$z$ を複素数とする．複素数平面上の $3$ 点 $\\mathrm{A}(1),\\ \\mathrm{B}(z),\\ \\mathrm{C}(z^2)$ が鋭角三角形をなすような $z$ の範囲を求め，図示せよ．\r\n\r\n## 6・3\r\n\r\n$11$ 個のボールが $11$ 個の箱にいくつかずつ，でたらめに入っている．空の箱がちょうど $2$ 個であることが分かっているときに，残りのどれかの箱に $3$ 個のボールが入っている条件つき確率を求めよ．"
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 7・1\r\n\r\n負でない整数 $p$ と正の整数 $n$ に対して，$S^p(n)=\\sum\\limits_{k=1}^n k^p$ とする．  \r\n(1) $\\sum\\limits_{r=0}^p {}_{p+1}\\mathrm{C}_r S^r(n)=(n+1)^{p+1}-1$ であることを示せ．  \r\n(2) $S^p(n)$ は文字 $n$ についての $p+1$ 次の整式であることを示し，さらに $n^{p+1}$ の係数を求めよ．\r\n\r\n## 7・2\r\n\r\n$c$ は定数で $c>1$ とする．$\\mathrm{P}$ を曲線 $C_1\\colon y=\\dfrac{c}{x}$（$x>0$）上の点とし，曲線 $y=\\dfrac{1}{x}$（$x<0$）を平行移動して得られる曲線のうち，点 $\\mathrm{P}$ で $C_1$ に接する（すなわち $\\mathrm{P}$ で共通接線をもつ）ものを $C_2$ とする．このとき，$C_2$ と曲線 $y=\\dfrac{1}{x}$（$x>0$）で囲まれる図形の面積は，$\\mathrm{P}$ の位置によらず一定であることを証明せよ．\r\n\r\n## 7・3\r\n\r\n正方形 $\\mathrm{ABCD}$ の内部の点 $\\mathrm{P}$ に対して $\\angle\\mathrm{CPD}$ が直角であるとき，$\\dfrac{\\mathrm{BP}}{\\mathrm{AP}}$ の最大値を求めよ．"
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 9・1\r\n\r\n$a$ を $3$ 以上の奇数の定数とする．方程式 $ax-2y=1$ を満たす自然数の組 $(x,\\ y)$ について，次の問に答えよ．  \r\n(1) 組 $(x,\\ y)$ は無数に存在することを示せ．  \r\n(2) 組 $(x,\\ y)$ の列 $(x_1,\\ y_1),\\ (x_2,\\ y_2),\\ \\cdots,\\ (x_n,\\ y_n),\\ \\cdots$ が，条件「$n\\geqq 2$ について $x_n$ は，$x_1,\\ x_2,\\ \\cdots,\\ x_{n-1}$ のどの項とも異なる」を満たすとする．このとき，極限値 $\\lim\\limits_{n\\to\\infty}\\dfrac{1}{n}\\left(\\dfrac{y_1}{x_1}+\\dfrac{y_2}{x_2}+\\dots+\\dfrac{y_n}{x_n}\\right)$ を $a$ を用いて表せ．必要ならば，$\\lim\\limits_{n\\to\\infty}\\dfrac{\\log n}{n}=0$ を利用してよい．ただし，対数は自然対数である．\r\n\r\n## 9・2\r\n\r\n数列 $\\{a_n\\}$ を $a_n=\\displaystyle\\int_0^1 x^3(1-x)^n\\,dx$（$n=1,\\ 2,\\ 3,\\ \\cdots$）によって定める．  \r\n(1) $a_n$ を求めよ．  \r\n(2) $\\sum\\limits_{n=1}^\\infty a_n$ を求めよ．  \r\n(3) $\\sum\\limits_{n=1}^\\infty (n+c)(a_n-a_{n+1})=\\dfrac{1}{3}$ を満たす定数 $c$ の値を求めよ．\r\n\r\n## 9・3\r\n\r\n数列 $a_1,\\ a_2,\\ \\dots$ を\r\n$$\r\na_n=\\dfrac{{}_{2n+1}\\mathrm{C}_n}{n!} \\quad (n=1,\\ 2,\\ \\dots)\r\n$$\r\nで定める．  \r\n(1) $n\\geqq 2$ とする．$\\dfrac{a_n}{a_{n-1}}$ を既約分数 $\\dfrac{q_n}{p_n}$ として表したときの分母 $p_n\\geqq 1$ と分子 $q_n$ を求めよ．  \r\n(2) $a_n$ が整数となる $n\\geqq 1$ をすべて求めよ．"
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 10・1\r\n\r\n実数 $r$ は $2\\pi r\\geqq 1$ を満たすとする．半径 $r$ の円の周上に $2$ 点 $\\mathrm{P},\\ \\mathrm{Q}$ を，弧 $\\mathrm{PQ}$ の長さが $1$ になるようにとる．点 $\\mathrm{R}$ が弧 $\\mathrm{PQ}$ 上を $\\mathrm{P}$ から $\\mathrm{Q}$ まで動くとき，弦 $\\mathrm{PR}$ が動いて通過する部分の面積を $S(r)$ とする．  \r\n$r$ が変化するとき，面積 $S(r)$ の最大値を求めよ．\r\n\r\n## 10・2\r\n\r\n半径 $r$，高さ $h$（$h>r$）の直円錐を，頂点を固定して平面上を図のように滑ることなく転がすとき，次の問に答えよ．  \r\n(1) 円錐の中心軸が $1$ 周して元の位置に戻るとき，円錐は中心軸の周りを何回転するか．  \r\n(2) (1) において，円錐が描く立体の体積を求めよ．\r\n\r\n## 10・3\r\n\r\n自然数 $N$ に対して，\r\n$$\r\n\\left(\\sum_{k=1}^{2N} k\\sin\\dfrac{(2k-1)\\pi}{2N}\\right)\\sin\\dfrac{\\pi}{2N}\r\n$$\r\nを求めよ．"
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 11・1\r\n\r\n座標空間において，円柱面 $C=\\{(x,\\ y,\\ z)\\mid x^2+y^2=4\\}$ を考える．  \r\n(1) $C$ 上の点 $\\mathrm{P}(2,\\ 0,\\ 0),\\ \\mathrm{Q}(x,\\ y,\\ 0),\\ \\mathrm{R}(x,\\ y,\\ z)$（ただし，$z\\geqq 0$）を考える．$\\mathrm{PR}=4$ のとき，$z$ を $\\theta=\\angle\\mathrm{POQ}$ の関数で表せ．ただし，$\\mathrm{O}$ は原点とする．  \r\n(2) 中心 $(2,\\ 0,\\ 0)$，半径 $4$ の球面 $S$ の内部および面上にある $C$ の部分の面積を求めよ．\r\n\r\n## 11・2\r\n\r\n袋 $\\mathrm{A}$ には $1$ から $n$ までの番号のついた $n$ 枚のカードが入っており，袋 $\\mathrm{B}$ には $1$ から $m$ までの番号のついた $m$ 枚のカードが入っている．ただし，$m>n$ とする．  \r\n$n$ 人の人が $1$ 回目に袋 $\\mathrm{A}$ から無作為にカードを $1$ 枚ずつ取り出し，$2$ 回目に袋 $\\mathrm{B}$ から無作為にカードを $1$ 枚ずつ取り出す．ただし，取り出したカードは元に戻さないものとする．  \r\n(1) すべての人について，$2$ 回目のカードの番号の方が $1$ 回目のカードの番号より大きいという事象の起こる確率 $P_{n,\\,m}$ を求めよ．  \r\n(2) $m=2n$ のときの $P_{n,\\,2n}$ に対して，$\\lim\\limits_{n\\to\\infty}\\sqrt[n]{P_{n,\\,2n}}$ を求めよ．\r\n\r\n## 11・3\r\n\r\n$n$ を自然数とする．$0$ でない複素数からなる集合 $M$ が次の条件 (I), (II), (III) を満たしている．  \r\n(I) 集合 $M$ は $n$ 個の要素からなる．  \r\n(II) $z\\in M$ のとき，$\\dfrac{1}{z}\\in M$ かつ $-z\\in M$ である．  \r\n(III) $z\\in M$ かつ $w\\in M$ のとき，$zw\\in M$ である．ただし，$z=w$ の場合もある．  \r\nこのとき，次の問に答えよ．  \r\n(1) $1\\in M$ および $-1\\in M$ を示せ．  \r\n(2) $n$ は偶数であることを示せ．  \r\n(3) $n=4$ のとき，集合 $M$ を求めよ．  \r\n(4) $n=6$ のとき，集合 $M$ を求めよ．"
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 13・1\r\n\r\n$n$ を $2$ 以上の自然数とする．$9^{k-1}$ と $9^k$ の桁数が等しいような $2\\leqq k\\leqq n$ の範囲の自然数 $k$ の個数を $a_n$ とするとき，$\\lim\\limits_{n\\to\\infty}\\dfrac{a_n}{n}$ を求めよ．\r\n\r\n## 13・2\r\n\r\n$n$ を $2$ 以上の整数とする．正 $2n$ 角形の $2n$ 個の頂点から $3$ 点を選び，これらを頂点とする三角形を作るとき，この三角形が鋭角三角形となる確率を $P_n$ とする．$\\lim\\limits_{n\\to\\infty}P_n$ を求めよ．\r\n\r\n## 13・3\r\n\r\n(1) 極形式で表された複素数 $z=r(\\cos\\theta+i\\sin\\theta)$ が $\\left|z+\\dfrac{1}{2}\\right|<\\dfrac{1}{2}$ を満たすための必要十分条件を $r$ と $\\theta$ を用いて表せ．また，$n$ を自然数とするとき，$|1+z+\\dots+z^n|^2$ を $r,\\ \\theta,\\ n$ を用いて表せ．  \r\n(2) 複素数 $z$ が $\\left|z+\\dfrac{1}{2}\\right|<\\dfrac{1}{2}$ を満たすならば，すべての自然数 $n$ に対し，\r\n$$\r\n|1+z+\\dots+z^n|<1\r\n$$\r\nが成り立つことを示せ．"
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 14・1\r\n\r\n$p$ を $3$ 以上の素数とする．$4$ 個の整数 $a,\\ b,\\ c,\\ d$ が次の $3$ 条件\r\n$$\r\na+b+c+d=0,\\quad ad-bc+p=0,\\quad a\\geqq b\\geqq c\\geqq d\r\n$$\r\nを満たすとき，$a,\\ b,\\ c,\\ d$ を $p$ を用いて表せ．\r\n\r\n## 14・2\r\n\r\n$2$ つの箱 $\\mathrm{L}$ と $\\mathrm{R}$，ボール $30$ 個，コイン投げで表と裏が等確率 $\\dfrac{1}{2}$ で出るコイン $1$ 枚を用意する．$x$ を $0$ 以上 $30$ 以下の整数とする．$\\mathrm{L}$ に $x$ 個，$\\mathrm{R}$ に $30-x$ 個のボールを入れ，次の操作（#）を繰り返す．  \r\n（#）箱 $\\mathrm{L}$ に入っているボールの個数を $z$ とする．コインを投げ，表が出れば箱 $\\mathrm{R}$ から箱 $\\mathrm{L}$ に，裏が出れば箱 $\\mathrm{L}$ から箱 $\\mathrm{R}$ に，$K(z)$ 個のボールを移す．ただし，$0\\leqq z\\leqq 15$ のとき $K(z)=z$，$16\\leqq z\\leqq 30$ のとき $K(z)=30-z$ とする．  \r\n$m$ 回の操作の後，箱 $\\mathrm{L}$ のボールの個数が $30$ である確率を $P_m(x)$ とする．たとえば $P_1(15)=P_2(15)=\\dfrac{1}{2}$ となる．以下の問 (1), (2), (3) に答えよ．  \r\n(1) $m\\geqq 2$ のとき，$x$ に対してうまく $y$ を選び，$P_m(x)$ を $P_{m-1}(y)$ で表せ．  \r\n(2) $n$ を自然数とするとき，$P_{2n}(10)$ を求めよ．  \r\n(3) $n$ を自然数とするとき，$P_{4n}(6)$ を求めよ．\r\n\r\n## 14・3\r\n\r\n$xyz$ 空間に $4$ 点 $\\mathrm{P}(0,\\ 0,\\ 2),\\ \\mathrm{A}(0,\\ 2,\\ 0),\\ \\mathrm{B}(\\sqrt{3},\\ -1,\\ 0),\\ \\mathrm{C}(-\\sqrt{3},\\ -1,\\ 0)$ をとる．四面体 $\\mathrm{PABC}$ の $x^2+y^2\\geqq 1$ を満たす部分の体積を求めよ．"
      }
    }
  }
};
