// This file is auto-generated by scripts/generate_data.js. Do not edit manually.
export const SUBJECTS_DATA = {
  "math1": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 1・1\r\n$a$ は実数の定数とする．方程式\r\n$$\r\n3(a-1)x^2+6x-a-2=0\r\n$$\r\nは $0$ と $1$ の間に少なくとも1つの解をもつことを示せ．\r\n\r\n## 1・2\r\n$a,\\ b$ は実数とする．2次方程式 $x^2+ax+b=0$ が $0<x<1,\\ 1<x<2$ の範囲に1つずつ解をもつ．このとき，2次方程式 $x^2+bx+a=0$ は異なる2つの実数解をもつことを示し，そのうち大きい方の解のとり得る値の範囲を求めよ．\r\n\r\n## 1・3\r\n次の連立方程式 $(*)$ を考える．\r\n$$\r\n(*)\\quad \\begin{cases} y=2x^2-1, \\\\ z=2y^2-1, \\\\ x=2z^2-1 \\end{cases}\r\n$$\r\n(1) $(x,\\ y,\\ z)=(a,\\ b,\\ c)$ が $(*)$ の実数解であるとき，$|a| \\leqq 1,\\ |b| \\leqq 1,\\ |c| \\leqq 1$ であることを示せ．  \r\n(2) $(*)$ は全部で8組の相異なる実数解 $(x,\\ y,\\ z)$ をもつことを示せ．"
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 2・1\r\n$k$ を実数とする．3次式 $f(x)=x^3-kx^2-1$ に対し，方程式 $f(x)=0$ の3つの解を $\\alpha,\\ \\beta,\\ \\gamma$ とする．$g(x)$ は $x^3$ の係数が $1$ である3次式で，方程式 $g(x)=0$ の3つの解が $\\alpha\\beta,\\ \\beta\\gamma,\\ \\gamma\\alpha$ であるものとする．\r\n(1) $g(x)$ を $k$ を用いて表せ．  \r\n(2) 2つの方程式 $f(x)=0$ と $g(x)=0$ が共通の解をもつような $k$ の値を求めよ．\r\n\r\n## 2・2\r\n$a,\\ b$ は定数（ただし，$b \\neq 0$）とする．整式 $f(x)=x^2+ax+b$ について次の問に答えよ．\r\n(1) $f(x^2)$ が $f(x)$ で割り切れるような $a,\\ b$ の値をすべて求めよ．  \r\n(2) 任意の自然数 $n$ に対して $f(x^n)$ が $f(x)$ で割り切れるような $a,\\ b$ の値をすべて求めよ．\r\n\r\n## 2・3\r\n$n$ は正の整数，$p$ は2以上の整数とする．$f(x),\\ g(x)$ は $n$ 次の整式で，ともに $x^n$ の係数は $1$ とする．このとき，$\\{f(x)\\}^p,\\ \\{g(x)\\}^p$ において\r\n$$\r\nx^{np-1},\\ x^{np-2},\\ \\cdots,\\ x^{np-n}\r\n$$\r\nの係数がそれぞれ一致しているならば，$f(x)=g(x)$ であることを示せ．"
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 3・1\r\n(1) $a_k,\\ b_k\\ (k=1,\\ 2,\\ 3,\\ \\cdots,\\ n)$ は実数とし，$A=\\sqrt{\\sum\\limits_{k=1}^n {a_k}^2},\\ B=\\sqrt{\\sum\\limits_{k=1}^n {b_k}^2}$ とおく．  \r\n$A \\neq 0,\\ B \\neq 0$ のとき，$\\left(\\dfrac{a_k}{A}-\\dfrac{b_k}{B}\\right)^2 \\geqq 0\\ (k=1,\\ 2,\\ 3,\\ \\cdots,\\ n)$ であることを用いて，  \r\n不等式 $\\sum\\limits_{k=1}^n a_k b_k \\leqq AB$ が成り立つことを示せ．  \r\n(2) 実数 $a_1,\\ a_2,\\ a_3,\\ a_4,\\ a_5$ が\r\n$$\r\na_1+a_2+a_3+a_4+a_5=10,\r\n$$\r\n$$\r\n{a_1}^2+{a_2}^2+{a_3}^2+{a_4}^2+{a_5}^2=25\r\n$$\r\nをともに満たすとき，$a_5$ の最大値を求めよ．\r\n\r\n## 3・2\r\n2以上の整数 $k$ に対して，$f_k(x)=x^k-kx+k-1$ とおく．\r\n(1) $f_k(x)$ は $(x-1)^2$ で割り切れることを示せ．  \r\n(2) $n$ は2以上の整数とする．$n$ 次多項式 $g(x)$ が $(x-1)^2$ で割り切れるためには，$g(x)$ が定数 $a_2,\\ a_3,\\ a_4,\\ \\cdots,\\ a_n$ を用いて\r\n$$\r\ng(x)=\\sum\\limits_{k=2}^n a_k f_k(x)\r\n$$\r\nの形に表されることが必要十分であることを示せ．\r\n\r\n## 3・3\r\n$\\alpha=2\\cos{20^\\circ}$ とおくとき，次の問に答えよ．\r\n(1) $\\alpha$ は3次方程式 $x^3-3x-1=0$ の解であることを示せ．  \r\n(2) $\\alpha$ は無理数であることを示せ．  \r\n(3) $\\alpha$ を解にもつ2次方程式 $ax^2+bx+c=0$（$a,\\ b,\\ c$ は有理数）は存在しないことを示せ．"
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 4・1\r\n$n$ は正の整数とする．正の整数 $k$ に対して $\\left(k+\\dfrac{1}{4}\\right)^2$ に最も近い整数を $a_k$ とするとき，\r\n$$\r\n\\sum\\limits_{k=1}^n (a_k-k^2)\r\n$$\r\nを $n$ で表せ．\r\n\r\n## 4・2\r\n数列 $\\{a_n\\}$ があって $a_1=2,\\ a_2=4$ であり，連続する3項 $a_n,\\ a_{n+1},\\ a_{n+2}$ は $n$ が奇数のとき等差数列をなし，$n$ が偶数のとき等比数列をなす．\r\n(1) $m$ を正の整数とする．$a_{2m-1},\\ a_{2m}$ を求めよ．  \r\n(2) $n$ を正の整数として，$a_1$ から $a_{2n}$ までの総和を求めよ．\r\n\r\n## 4・3\r\n$n$ は3以上の整数とする．実数 $x_1,\\ x_2,\\ x_3,\\ \\cdots,\\ x_n$ が条件\r\n$$\r\nx_{k-1}-2x_k+x_{k+1}>0\\ (2 \\leqq k \\leqq n-1)\r\n$$\r\nを満たすとし，$x_1,\\ x_2,\\ x_3,\\ \\cdots,\\ x_n$ の最小値を $m$ とする．  \r\nこのとき，$x_l=m$ となる整数 $l\\ (1 \\leqq l \\leqq n)$ の個数は1または2であることを示せ．"
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 5・1\r\n平面上に互いに外接する半径 $1$ の2つの円 $T$ と $S_1$ がある．$T$ に点 $\\mathrm{P}$ で接し，$S_1$ に点 $\\mathrm{Q}_1$ で接する図のような直線 $l$ を考える．$l,\\ T,\\ S_1$ の3つで囲まれた領域内に中心をもち，$l,\\ T,\\ S_1$ のすべてに接する円を $S_2$ とし，$S_2$ と $l$ との接点を $\\mathrm{Q}_2$ とする．一般に，$n=2,\\ 3,\\ 4,\\ \\cdots$ に対して，$l,\\ T,\\ S_{n-1}$ の3つで囲まれた領域内に中心をもち，$l,\\ T,\\ S_{n-1}$ のすべてに接する円を $S_n$ とし，$S_n$ と $l$ との接点を $\\mathrm{Q}_n$ とする．また，$S_n$ の半径を $r_n$ とし，線分 $\\mathrm{P}\\mathrm{Q}_n$ の長さを $q_n$ とする．\r\n(1) $r_n$ を $q_n$ を用いて表せ．  \r\n(2) $q_n,\\ r_n$ をそれぞれ $n$ を用いて表せ．\r\n\r\n## 5・2\r\n正の整数 $n$ に対して，\r\n$$\r\n(1+\\sqrt{2})^n=x_n+y_n\\sqrt{2}\r\n$$\r\nが成り立つように整数 $x_n,\\ y_n$ を定める．\r\n(1) $x_{n+1},\\ y_{n+1}$ を $x_n,\\ y_n$ で表せ．  \r\n(2) ${x_n}^2-2{y_n}^2=(-1)^n$ であることを示せ．  \r\n(3) 任意の正の整数 $n$ に対して，$\\dfrac{x_{n+1}}{y_{n+1}}$ は $\\dfrac{x_n}{y_n}$ よりも $\\sqrt{2}$ のよい近似であることを示せ．\r\n\r\n## 5・3\r\n数列 $\\{x_n\\}$ が次のように定義されている．  \r\n$x_1=0,\\ k=1,\\ 2,\\ 3,\\ \\cdots$ に対して，\r\n$$\r\nx_n = \\begin{cases} x_k+1\\ (n=2k\\ \\text{のとき}), \\\\ x_k+2\\ (n=2k+1\\ \\text{のとき}). \\end{cases}\r\n$$\r\nこのとき，$n=2,\\ 3,\\ 4,\\ \\cdots$ に対して，$x_n \\leqq 2\\log_2{n}-1$ が成り立つことを示せ．"
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 6・1\r\n$f(x)=x^3-3x^2+2x$ とおく．曲線 $y=f(x)$ 上の点 $\\mathrm{P}_n(x_n,\\ f(x_n))$（$n$ は自然数）を次の条件 (a), (b) で定める．\r\n(a) $\\mathrm{P}_1$ を $(0,\\ 0)$ とする．\r\n(b) $n \\geqq 1$ について，$\\mathrm{P}_n$ における曲線 $y=f(x)$ の接線は，$\\mathrm{P}_n$ 以外の1点でこの曲線と交わる．この交点を $\\mathrm{P}_{n+1}$ とおく．\r\n(1) $x_n$ と $x_{n+1}$ の関係式を求めよ．  \r\n(2) $\\lim\\limits_{n \\to \\infty} \\dfrac{x_{n+1}}{x_n}$ を求めよ．\r\n\r\n## 6・2\r\n数列 $\\dfrac{1}{1},\\ \\dfrac{1}{2},\\ \\dfrac{2}{2},\\ \\dfrac{1}{3},\\ \\dfrac{2}{3},\\ \\dfrac{3}{3},\\ \\dfrac{1}{4},\\ \\dfrac{2}{4},\\ \\dfrac{3}{4},\\ \\dfrac{4}{4},\\ \\dfrac{1}{5},\\ \\cdots$ の初項から第 $n$ 項までのうちで値が $\\dfrac{1}{4}$ に等しい項の個数を $a_n$ とするとき，$\\lim\\limits_{n \\to \\infty} \\dfrac{a_n}{\\sqrt{n}}$ を求めよ．\r\n\r\n## 6・3\r\n(1) $n$ 桁の自然数のうち，各位の数字がすべて $1$ と異なるものの個数を求めよ．  \r\n(2) 自然数の逆数からなる級数\r\n$$\r\n\\dfrac{1}{1}+\\dfrac{1}{2}+\\dfrac{1}{3}+\\cdots+\\dfrac{1}{m}+\\cdots\r\n$$\r\nから，分母に数字 $1$ が現れる項をすべて除いて得られる級数\r\n$$\r\n\\dfrac{1}{2}+\\dfrac{1}{3}+\\dfrac{1}{4}+\\dfrac{1}{5}+\\dfrac{1}{6}+\\dfrac{1}{7}+\\dfrac{1}{8}+\\dfrac{1}{9}+\\dfrac{1}{20}+\\dfrac{1}{22}+\\dfrac{1}{23}+\\cdots\r\n$$\r\nについて，その部分和は，$40$ を超えないことを示せ．"
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 7・1\r\n七角柱の9個の面に $1$ から $9$ までの番号が書いてあるものとする．この9個の面に1つずつ，異なる4色の中から1色ずつ選んで塗っていく．このとき，どの辺を共有する2面の組も同一色では塗られない塗り方の数を求めよ．\r\n\r\n## 7・2\r\n(1) 正九角形の3つの頂点でできる ${}_9\\mathrm{C}_3\\ (=84)$ 個の三角形のうち，鈍角三角形は全部でいくつあるか．  \r\n(2) $n$ は正の整数とする．正 $2n+1$ 角形の3つの頂点でできる ${}_{2n+1}\\mathrm{C}_3$ 個の三角形のうち，鋭角三角形は全部でいくつあるか．\r\n\r\n## 7・3\r\n$n$ を正の整数とし，$n$ 個のボールを3つの箱に分けて入れる問題を考える．ただし，1個のボールも入らない箱があってもよいものとする．\r\n(1) $1$ から $n$ まで相異なる番号のついた $n$ 個のボールを，区別のつかない3つの箱に入れる場合，その入れ方は全部で何通りあるか．  \r\n(2) $n=6m$（$m$ は正の整数）であるとき，区別のつかない $n$ 個のボールを，区別のつかない3つの箱に入れる場合，その入れ方は全部で何通りあるか．$m$ で表せ．"
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 8・1\r\n$n$ を3以上の奇数とする．袋の中に番号 $0,\\ 1,\\ 2,\\ \\cdots,\\ n$ のついた札がそれぞれ1枚ずつ入っている．この袋から2枚の札を取り出したとき，それらの札の番号の和を $n$ で割った余りが $k$ である確率を求めよ．ただし，$k$ は $0 \\leqq k \\leqq n-1$ を満たす整数とする．\r\n\r\n## 8・2\r\n数直線上を動く点があり，はじめは原点 $\\mathrm{O}$ にある．サイコロを振り，$1$ または $2$ の目が出たら $+1$ だけ移動させ，$3$ または $4$ の目が出たら動かさず，$5$ または $6$ の目が出たら $-1$ だけ移動させる．サイコロを6回振るとき，点が6回目にはじめて座標 $2$ の点に移動する確率を求めよ．\r\n\r\n## 8・3\r\n数 $1,\\ 2,\\ 3,\\ \\cdots,\\ 2a$（$a$ は正の整数）のいずれについても，それが記入されたカードが1枚ずつ，計 $2a$ 枚のカードが箱に入っている．ここから無作為にカードを1枚取り出して記入された数を記録してもとに戻す操作を $b$ 回（$b$ は2以上の整数）行う．  \r\n記録された $b$ 個の数の最大値 $M$ と最小値 $m$ について，$M \\leqq 2m$ となる確率を $a,\\ b$ で表せ．"
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 9・1\r\n$1,\\ 2,\\ 3$ という3枚のカードがこの順に横一列に並んでいる．サイコロを振って，$3$ の倍数の目が出たら左端のカードと中央のカードを入れ換え，その他の目が出たら右端のカードと中央のカードを入れ換える．  \r\nこの試行を $n$ 回（$n$ は正の整数）繰り返したのち，$2$ が中央にある確率 $a_n$ を $n$ で表せ．\r\n\r\n## 9・2\r\n$n$ は3以上の整数とする．箱の中に $n$ 個の球があり，連続した整数 $a,\\ a+1,\\ a+2,\\ \\cdots,\\ a+n-1$ がそれぞれの球に1つずつ記されている．以下では，$n$ の値は知られているが，$a$ の値は知られていないものとする．\r\n(1) この箱から無作為に1個の球を取り出し，記されている整数を調べる．ただし，取り出された球は箱に戻さない．これを繰り返して $X$ 回目（$X$ は正の整数）に初めて $a$ の値がわかるものとする．  \r\nこのとき，$X$ の期待値を求めよ．  \r\n(2) この箱から無作為に1個の球を取り出し，記されている整数を調べて箱に戻すことを $k$ 回（$k$ は正の整数）繰り返す．この操作により $a$ の値がわかる確率を求めよ．\r\n\r\n## 9・3\r\n$N$ を正の整数とする．袋の中に赤玉1個と白玉2個が入っている．「この袋から玉を1個取り出して戻し，出た玉と同じ色の玉を袋の中に1個追加する」という操作を $N$ 回繰り返した後，赤玉が袋の中にちょうど $m$ 個（$1 \\leqq m \\leqq N+1$）ある確率を $N,\\ m$ を用いて表せ．"
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 10・1\r\n正の数 $s,\\ t$ に対して，$x$ の4次方程式\r\n$$\r\n\\text{(A)}\\quad x^4-2(s+t-1)x^2+2st+1=0\r\n$$\r\nを考える．\r\n(1) 方程式 (A) が異なる4つの実数解をもつような $(s,\\ t)$ の存在する範囲を，$st$ 平面上に図示せよ．  \r\n(2) $\\dfrac{1}{2} \\leqq t \\leqq 2$ であるすべての $t$ に対して，方程式 (A) が異なる4つの実数解をもつとき，$s$ の値の範囲を求めよ．  \r\n(3) $\\dfrac{1}{2} \\leqq t \\leqq 2$ である少なくとも1つの $t$ に対して，方程式 (A) が異なる4つの実数解をもつとき，$s$ の値の範囲を求めよ．\r\n\r\n## 10・2\r\n正方形のタイル $n$ 枚（$n \\geqq 2$）が1列に並べてある．6色の塗料の全て，またはこのうちの何色かを用いてこの $n$ 枚のタイルを塗る．\r\n(1) 隣り合う2枚のタイルの色がすべて異なるような塗り方の数 $a_n$ を求めよ．  \r\n(2) 隣り合う2枚のタイルの色がすべて異なり，かつ両端のタイルの色が異なるような塗り方の数を $b_n$ とする．$b_n$ を求めよ．\r\n\r\n## 10・3\r\n袋の中に，青色のカードが4枚，黄色のカードが3枚，赤色のカードが1枚の計8枚のカードが入っている．この袋から無作為にカードを1枚取り出して，その色を記録し袋に戻す試行を繰り返し行う．ただし，赤色のカードが取り出された場合はその回で試行を終了する．また，黄色のカードが2回連続して取り出された場合もその回で試行を終了する．このとき，ちょうど $n$ 回目（$n \\geqq 1$）に試行を終了する確率を求めよ．"
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 11・1\r\n$n$ 次の整式 $f(x)=a_0+a_1x+a_2x^2+\\cdots+a_nx^n$（$a_0,\\ a_1,\\ a_2,\\ \\cdots,\\ a_n$ は定数，$a_n \\neq 0$）が次の条件を満たしている．\r\n$$\r\n\\begin{aligned}\r\n&\\text{(i)}\\quad f(1)=1 \\\\\r\n&\\text{(ii)}\\quad f(1-x)=f(x) \\\\\r\n&\\text{(iii)}\\quad x^4 f\\left(\\dfrac{1}{x}\\right)=f(x)\r\n\\end{aligned}\r\n$$\r\n(1) $a_0$ の値を求めよ．  \r\n(2) $f(x)$ を求めよ．\r\n\r\n## 11・2\r\n1つのサイコロを繰り返し6回投げ，出た目を順に $a,\\ b,\\ c,\\ d,\\ e,\\ f$ とする．\r\n(1) $a,\\ b$ をこの順に並べて十進法で表された2桁の整数\r\n$$\r\nN_2=ab\\ (=10a+b)\r\n$$\r\nを作る．$N_2$ が7の倍数となる確率を求めよ．  \r\n(2) $a,\\ b,\\ c$ をこの順に並べて十進法で表された3桁の整数\r\n$$\r\nN_3=abc\\ (=100a+10b+c)\r\n$$\r\nを作る．$N_3$ が7の倍数となる確率を求めよ．  \r\n(3) $a,\\ b,\\ c,\\ d,\\ e,\\ f$ をこの順に並べて十進法で表された6桁の整数 $N_6=abcdef$ を作る．$N_6$ が7の倍数となる確率を求めよ．\r\n\r\n## 11・3\r\n$\\mathrm{A},\\ \\mathrm{B},\\ \\mathrm{C}$ の3つのチームが参加する野球の大会を開催する．以下の方式で試合を行い，2連勝したチームが出た時点で，そのチームを優勝チームとして大会は終了する．\r\n(a) 1試合目で $\\mathrm{A}$ と $\\mathrm{B}$ が対戦する．\r\n(b) 2試合目で，1試合目の勝者と，1試合目で待機していた $\\mathrm{C}$ が対戦する．\r\n(c) $k$ 試合目で優勝チームが決まらない場合は，$k$ 試合目の勝者と，$k$ 試合目で待機していたチームが $k+1$ 試合目で対戦する．ここで $k$ は2以上の整数とする．\r\nなお，すべての対戦において，それぞれのチームが勝つ確率は $\\dfrac{1}{2}$ で，引き分けはないものとする．\r\n(1) $n$ を2以上の整数とする．ちょうど $n$ 試合目で $\\mathrm{A}$ が優勝する確率を求めよ．  \r\n(2) $m$ を正の整数とする．総試合数が $3m$ 以下で $\\mathrm{A}$ が優勝したとき，$\\mathrm{A}$ の最後の対戦相手が $\\mathrm{B}$ である条件付き確率を求めよ．"
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 12・1\r\n正の実数 $x,\\ y$ が $\\dfrac{x^2+xy+2y^2}{x^2-xy+2y^2} \\geqq 2$ を満たしながら変化するとき，次の問に答えよ．\r\n(1) $t=\\dfrac{x}{y}$ のとり得る値の範囲を求めよ．  \r\n(2) 不等式 $x^3-3axy^2+a^2y^3 \\geqq 0$ がつねに成り立つための正の実数 $a$ に関する条件を求めよ．\r\n\r\n## 12・2\r\n正の整数 $a$ と $b$ は互いに素であるとし，正の整数からなる数列 $\\{x_n\\}$ を\r\n$$\r\nx_1=x_2=1,\\quad x_{n+2}=ax_{n+1}+bx_n\\ (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nで定める．このときすべての正の整数 $n$ に対して $x_{n+1}$ と $x_n$ が互いに素であることを示せ．\r\n\r\n## 12・3\r\n$1$ から $n$ までの番号がついている $n$ 個の箱と，$1$ から $n$ までの番号がついている $n$ 個の球があり，それぞれの箱に球を1個ずつ無作為に入れるものとする．箱の番号と球の番号がすべて異なる入れ方の総数を $D_n$ とするとき，次の問に答えよ．\r\n(1) $D_4$ を求めよ．  \r\n(2) $D_n,\\ D_{n-1},\\ D_{n-2}\\ (n \\geqq 3)$ の間に成り立つ関係式を求めよ．  \r\n(3) 箱の番号と球の番号がすべて異なる確率を $P_n$ とするとき，\r\n$$\r\nP_n=\\dfrac{1}{2!}-\\dfrac{1}{3!}+\\dfrac{1}{4!}-\\dfrac{1}{5!}+\\cdots+\\dfrac{(-1)^n}{n!}\\ (n \\geqq 2)\r\n$$\r\nが成り立つことを示せ．"
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 13・1\r\n4枚のカードがあって，$1$ から $4$ までの整数が1つずつ書かれている．このカードから1枚引いて，カードに書かれた整数を記録し，カードをもとに戻す．この試行を $n$ 回繰り返し，記録した順に整数を並べて得られる数列を，$a_1,\\ a_2,\\ \\cdots,\\ a_n$ とする．\r\n(1) $n$ は2以上の整数とする．\r\n$$\r\na_1 \\leqq a_2 \\leqq \\cdots \\leqq a_n\r\n$$\r\nとなる確率を求めよ．  \r\n(2) $n$ は3以上の整数とする．\r\n$$\r\na_1 \\leqq a_2 \\leqq \\cdots \\leqq a_{n-1} \\quad \\text{かつ} \\quad a_{n-1} > a_n\r\n$$\r\nとなる確率を求めよ．\r\n\r\n## 13・2\r\n(1) $a<b,\\ c<d$ に対して，$ad+bc<ac+bd$ が成り立つことを示せ．  \r\n(2) $n$ は正の整数とする．  \r\n正の整数 $1,\\ 2,\\ 3,\\ \\cdots,\\ n$ について，その順列を考え，並んだ正の整数を先頭から順に $a_1,\\ a_2,\\ a_3,\\ \\cdots,\\ a_n$ とし，\r\n$$\r\nS_n=\\sum\\limits_{k=1}^n k a_k\r\n$$\r\nとする．  \r\n$S_n$ を最大にする $a_1,\\ a_2,\\ a_3,\\ \\cdots,\\ a_n$ を求めよ．\r\n\r\n## 13・3\r\n$1$ から $n\\ (n \\geqq 3)$ までのすべての整数を1つずつ書いた $n$ 枚のカードの中から，同時に3枚のカードを取り出す．取り出した3枚のカードに書いてある数をそれぞれ長さとする3つの線分で，三角形を作ることを考える．三角形ができるようなカードの取り出し方の場合の数を $S_n$，三角形ができる確率を $P_n$ とするとき，次の問に答えよ．\r\n(1) $S_{n+1}-S_n$ を $n$ を用いて表せ．  \r\n(2) $m$ は2以上の整数とする．$P_{2m}$ および $\\lim\\limits_{m \\to \\infty} P_{2m}$ を求めよ．"
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": "## 14・1\r\n$n=1,\\ 2,\\ 3,\\ \\cdots$ に対して $x$ の整式 $P_n(x)=x^3-nx^2-(2n+12)x-8$ を考える．\r\n(1) 3次方程式 $P_n(x)=0$ の正の実数解はただ1つであることを示せ．  \r\n(2) $t$ が $P_n(x)=0$ の解であるとき，$P_n\\left(-\\dfrac{4}{t+2}\\right)$ を求めよ．  \r\n(3) $P_n(x)=0$ の正の実数解を $\\alpha_n$ とするとき，$P_n(x)=0$ の最小の実数解 $\\beta_n$ を $\\alpha_n$ で表せ．さらに，$\\lim\\limits_{n \\to \\infty} \\beta_n$ を求めよ．\r\n\r\n## 14・2\r\n数列 $\\{a_n\\}$ は，\r\n$$\r\n\\sum\\limits_{k=1}^n a_k=\\left(a_n+\\dfrac{1}{4}\\right)^2\\ (n=1,\\ 2,\\ 3,\\ \\cdots)\r\n$$\r\nを満たしている．\r\n(1) $\\{a_n\\}$ の項はすべて正とする．一般項 $a_n$ を求めよ．  \r\n(2) $\\{a_n\\}$ の最初の100項のうち，1つは負で他はすべて正とする．$a_{100}$ を求めよ．\r\n\r\n## 14・3\r\n$1$ と $0$ を5個並べた列 $10110$ をある人が繰り返し書き写すとする．ただし，この列を $S$ で表し，これの第1回の写しを $S_1$ で表すとき，第2回目に書き写すときは $S_1$ を書き写す．$S_1$ の写しを $S_2$ とするとき，第3回目には $S_2$ を書き写す．以下，同様に続ける．  \r\nこの人が $0$ を $1$ に写しまちがえる確率は $p\\ (0<p<1)$ であり，$1$ を $0$ に写しまちがえる確率は $q\\ (0<q<1)$ であるが，それ以外の写しまちがいはないものとする．  \r\n第 $n$ 回目の写し $S_n$ が $S$ に一致する確率を $C(n)$ とするとき，極限値 $\\lim\\limits_{n \\to \\infty} C(n)$ を求めよ．"
      }
    }
  },
  "math2": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  },
  "math3": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  },
  "science_math": {
    "lec01": {
      "number": 1,
      "slug": "lec01",
      "label": "第1講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec02": {
      "number": 2,
      "slug": "lec02",
      "label": "第2講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec03": {
      "number": 3,
      "slug": "lec03",
      "label": "第3講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec04": {
      "number": 4,
      "slug": "lec04",
      "label": "第4講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec05": {
      "number": 5,
      "slug": "lec05",
      "label": "第5講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec06": {
      "number": 6,
      "slug": "lec06",
      "label": "第6講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec07": {
      "number": 7,
      "slug": "lec07",
      "label": "第7講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec08": {
      "number": 8,
      "slug": "lec08",
      "label": "第8講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec09": {
      "number": 9,
      "slug": "lec09",
      "label": "第9講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec10": {
      "number": 10,
      "slug": "lec10",
      "label": "第10講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec11": {
      "number": 11,
      "slug": "lec11",
      "label": "第11講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec12": {
      "number": 12,
      "slug": "lec12",
      "label": "第12講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec13": {
      "number": 13,
      "slug": "lec13",
      "label": "第13講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    },
    "lec14": {
      "number": 14,
      "slug": "lec14",
      "label": "第14講",
      "availableTypes": [
        "self_study",
        "example",
        "exercise"
      ],
      "contents": {
        "self_study": "",
        "example": "",
        "exercise": ""
      }
    }
  }
};
