const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");

const BASE_DIR = path.join(__dirname, "..");
const DATA_DIR = path.join(BASE_DIR, "data");
const OUTPUT_FILE = path.join(BASE_DIR, "lib", "subjectsData.js");

const CONTENT_TYPES = ["self_study", "example", "exercise"];

function collectSubjectsData() {
  const result = {};

  if (!fs.existsSync(DATA_DIR)) return result;

  const subjectDirs = fs.readdirSync(DATA_DIR, { withFileTypes: true });

  for (const sDir of subjectDirs) {
    if (!sDir.isDirectory()) continue;
    const subjectId = sDir.name;
    result[subjectId] = {};

    const subjectPath = path.join(DATA_DIR, subjectId);
    const lectureDirs = fs.readdirSync(subjectPath, { withFileTypes: true });

    for (const lDir of lectureDirs) {
      if (!lDir.isDirectory() || !lDir.name.startsWith("lec")) continue;
      const lectureSlug = lDir.name;
      const lecturePath = path.join(subjectPath, lectureSlug);
      const lecNum = parseInt(lectureSlug.replace("lec", ""), 10);

      const contents = {};
      const availableTypes = [];

      for (const typeId of CONTENT_TYPES) {
        const mdPath = path.join(lecturePath, `${typeId}.md`);
        if (fs.existsSync(mdPath)) {
          const raw = fs.readFileSync(mdPath, "utf-8");
          // gray-matter を使って Frontmatter (--- ... ---) を除去し、本文のみを取得
          const { content } = matter(raw);
          contents[typeId] = content.trim();
          availableTypes.push(typeId);
        }
      }

      result[subjectId][lectureSlug] = {
        number: lecNum,
        slug: lectureSlug,
        label: `第${lecNum}講`,
        availableTypes,
        contents,
      };
    }
  }

  return result;
}

const subjectsData = collectSubjectsData();

const jsContent = `// This file is auto-generated by scripts/generate_data.js. Do not edit manually.
export const SUBJECTS_DATA = ${JSON.stringify(subjectsData, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, jsContent, "utf-8");

let totalLectures = 0;
for (const sub of Object.keys(subjectsData)) {
  totalLectures += Object.keys(subjectsData[sub]).length;
}

console.log(`Successfully generated subjectsData.js (${Object.keys(subjectsData).length} subjects, ${totalLectures} lectures)`);
